use serde::{Deserialize, Serialize};
use strum_macros::{AsRefStr, Display, EnumIter, EnumString, IntoStaticStr};

#[derive(
    Copy,
    Clone,
    PartialEq,
    Eq,
    Hash,
    Debug,
    PartialOrd,
    Ord,
    Serialize,
    Deserialize,
    AsRefStr,
    Display,
    EnumIter,
    EnumString,
    IntoStaticStr,
)]
pub enum Cycle {
    Advent,
    Christmas,
    Epiphany,
    Easter,
}

#[derive(Copy, Clone, PartialEq, Eq, Hash, Debug, Serialize, Deserialize)]
struct LiturgicalWeekIndex {
    cycle: Cycle,
    week: u8,
    proper: Option<u8>,
}

#[derive(
    Copy,
    Clone,
    PartialEq,
    Eq,
    Hash,
    Debug,
    PartialOrd,
    Ord,
    Serialize,
    Deserialize,
    AsRefStr,
    Display,
    EnumIter,
    EnumString,
    IntoStaticStr,
)]
pub enum LiturgicalWeek {
    Advent1,
    Advent2,
    Advent3,
    Advent4,
    Christmas,
    Christmas1,
    Christmas2,
    Epiphany,
    Epiphany1,
    Epiphany2,
    Epiphany3,
    Epiphany4,
    Epiphany5,
    Epiphany6,
    Epiphany7,
    Epiphany8,
    LastEpiphany,
    Lent1,
    Lent2,
    Lent3,
    Lent4,
    Lent5,
    HolyWeek,
    Easter,
    Easter2,
    Easter3,
    Easter4,
    Easter5,
    Easter6,
    Easter7,
    Pentecost,
    TrinitySunday,
    Pentecost2,
    Pentecost3,
    Pentecost4,
    Pentecost5,
    Pentecost6,
    Pentecost7,
    Pentecost8,
    Pentecost9,
    Pentecost10,
    Pentecost11,
    Pentecost12,
    Pentecost13,
    Pentecost14,
    Pentecost15,
    Pentecost16,
    Pentecost17,
    Pentecost18,
    Pentecost19,
    Pentecost20,
    Pentecost21,
    Pentecost22,
    Pentecost23,
    Pentecost24,
    Pentecost25,
    Pentecost26,
    Pentecost27,
    LastPentecost,
    None,
}
