[package]
name = "language"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"]}
strum = "0.24"
strum_macros = "0.24"

[dev-dependencies]
liturgy = { path = "../liturgy" }
