use calendar::{LiturgicalDayId, Year, YearType};

use crate::{Lectionary, ReadingType};

pub const BCP1979_30_DAY_PSALTER: Lectionary = Lectionary {
    year_type: YearType::None,
    readings: &[
        (
            LiturgicalDayId::DayOfMonth(1),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 1",
        ),
        (
            LiturgicalDayId::DayOfMonth(1),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 2",
        ),
        (
            LiturgicalDayId::DayOfMonth(1),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 3",
        ),
        (
            LiturgicalDayId::DayOfMonth(1),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 4",
        ),
        (
            LiturgicalDayId::DayOfMonth(1),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 5",
        ),
        (
            LiturgicalDayId::DayOfMonth(1),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 6",
        ),
        (
            LiturgicalDayId::DayOfMonth(1),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 7",
        ),
        (
            LiturgicalDayId::DayOfMonth(1),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 8",
        ),
        (
            LiturgicalDayId::DayOfMonth(2),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 9",
        ),
        (
            LiturgicalDayId::DayOfMonth(2),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 10",
        ),
        (
            LiturgicalDayId::DayOfMonth(2),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 11",
        ),
        (
            LiturgicalDayId::DayOfMonth(2),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 12",
        ),
        (
            LiturgicalDayId::DayOfMonth(2),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 13",
        ),
        (
            LiturgicalDayId::DayOfMonth(2),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 14",
        ),
        (
            LiturgicalDayId::DayOfMonth(3),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 15",
        ),
        (
            LiturgicalDayId::DayOfMonth(3),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 16",
        ),
        (
            LiturgicalDayId::DayOfMonth(3),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 17",
        ),
        (
            LiturgicalDayId::DayOfMonth(3),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 18",
        ),
        (
            LiturgicalDayId::DayOfMonth(4),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 19",
        ),
        (
            LiturgicalDayId::DayOfMonth(4),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 20",
        ),
        (
            LiturgicalDayId::DayOfMonth(4),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 21",
        ),
        (
            LiturgicalDayId::DayOfMonth(4),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 22",
        ),
        (
            LiturgicalDayId::DayOfMonth(4),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 23",
        ),
        (
            LiturgicalDayId::DayOfMonth(5),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 24",
        ),
        (
            LiturgicalDayId::DayOfMonth(5),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 25",
        ),
        (
            LiturgicalDayId::DayOfMonth(5),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 26",
        ),
        (
            LiturgicalDayId::DayOfMonth(5),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 27",
        ),
        (
            LiturgicalDayId::DayOfMonth(5),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 28",
        ),
        (
            LiturgicalDayId::DayOfMonth(5),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 29",
        ),
        (
            LiturgicalDayId::DayOfMonth(6),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 30",
        ),
        (
            LiturgicalDayId::DayOfMonth(6),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 31",
        ),
        (
            LiturgicalDayId::DayOfMonth(6),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 32",
        ),
        (
            LiturgicalDayId::DayOfMonth(6),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 33",
        ),
        (
            LiturgicalDayId::DayOfMonth(6),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 34",
        ),
        (
            LiturgicalDayId::DayOfMonth(7),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 35",
        ),
        (
            LiturgicalDayId::DayOfMonth(7),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 36",
        ),
        (
            LiturgicalDayId::DayOfMonth(7),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 37",
        ),
        (
            LiturgicalDayId::DayOfMonth(8),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 38",
        ),
        (
            LiturgicalDayId::DayOfMonth(8),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 39",
        ),
        (
            LiturgicalDayId::DayOfMonth(8),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 40",
        ),
        (
            LiturgicalDayId::DayOfMonth(8),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 41",
        ),
        (
            LiturgicalDayId::DayOfMonth(8),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 42",
        ),
        (
            LiturgicalDayId::DayOfMonth(8),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 43",
        ),
        (
            LiturgicalDayId::DayOfMonth(9),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 44",
        ),
        (
            LiturgicalDayId::DayOfMonth(9),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 45",
        ),
        (
            LiturgicalDayId::DayOfMonth(9),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 46",
        ),
        (
            LiturgicalDayId::DayOfMonth(9),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 47",
        ),
        (
            LiturgicalDayId::DayOfMonth(9),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 48",
        ),
        (
            LiturgicalDayId::DayOfMonth(9),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 49",
        ),
        (
            LiturgicalDayId::DayOfMonth(10),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 50",
        ),
        (
            LiturgicalDayId::DayOfMonth(10),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 51",
        ),
        (
            LiturgicalDayId::DayOfMonth(10),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 52",
        ),
        (
            LiturgicalDayId::DayOfMonth(10),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 53",
        ),
        (
            LiturgicalDayId::DayOfMonth(10),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 54",
        ),
        (
            LiturgicalDayId::DayOfMonth(10),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 55",
        ),
        (
            LiturgicalDayId::DayOfMonth(11),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 56",
        ),
        (
            LiturgicalDayId::DayOfMonth(11),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 57",
        ),
        (
            LiturgicalDayId::DayOfMonth(11),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 58",
        ),
        (
            LiturgicalDayId::DayOfMonth(11),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 59",
        ),
        (
            LiturgicalDayId::DayOfMonth(11),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 60",
        ),
        (
            LiturgicalDayId::DayOfMonth(11),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 61",
        ),
        (
            LiturgicalDayId::DayOfMonth(12),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 62",
        ),
        (
            LiturgicalDayId::DayOfMonth(12),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 63",
        ),
        (
            LiturgicalDayId::DayOfMonth(12),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 64",
        ),
        (
            LiturgicalDayId::DayOfMonth(12),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 65",
        ),
        (
            LiturgicalDayId::DayOfMonth(12),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 66",
        ),
        (
            LiturgicalDayId::DayOfMonth(12),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 67",
        ),
        (
            LiturgicalDayId::DayOfMonth(13),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 68",
        ),
        (
            LiturgicalDayId::DayOfMonth(13),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 69",
        ),
        (
            LiturgicalDayId::DayOfMonth(13),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 70",
        ),
        (
            LiturgicalDayId::DayOfMonth(14),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 71",
        ),
        (
            LiturgicalDayId::DayOfMonth(14),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 72",
        ),
        (
            LiturgicalDayId::DayOfMonth(14),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 73",
        ),
        (
            LiturgicalDayId::DayOfMonth(14),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 74",
        ),
        (
            LiturgicalDayId::DayOfMonth(15),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 75",
        ),
        (
            LiturgicalDayId::DayOfMonth(15),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 76",
        ),
        (
            LiturgicalDayId::DayOfMonth(15),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 77",
        ),
        (
            LiturgicalDayId::DayOfMonth(15),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 78",
        ),
        (
            LiturgicalDayId::DayOfMonth(16),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 79",
        ),
        (
            LiturgicalDayId::DayOfMonth(16),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 80",
        ),
        (
            LiturgicalDayId::DayOfMonth(16),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 81",
        ),
        (
            LiturgicalDayId::DayOfMonth(16),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 82",
        ),
        (
            LiturgicalDayId::DayOfMonth(16),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 83",
        ),
        (
            LiturgicalDayId::DayOfMonth(16),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 84",
        ),
        (
            LiturgicalDayId::DayOfMonth(16),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 85",
        ),
        (
            LiturgicalDayId::DayOfMonth(17),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 86",
        ),
        (
            LiturgicalDayId::DayOfMonth(17),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 87",
        ),
        (
            LiturgicalDayId::DayOfMonth(17),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 88",
        ),
        (
            LiturgicalDayId::DayOfMonth(17),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 89",
        ),
        (
            LiturgicalDayId::DayOfMonth(18),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 90",
        ),
        (
            LiturgicalDayId::DayOfMonth(18),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 91",
        ),
        (
            LiturgicalDayId::DayOfMonth(18),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 92",
        ),
        (
            LiturgicalDayId::DayOfMonth(18),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 93",
        ),
        (
            LiturgicalDayId::DayOfMonth(18),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 94",
        ),
        (
            LiturgicalDayId::DayOfMonth(19),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 95",
        ),
        (
            LiturgicalDayId::DayOfMonth(19),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 96",
        ),
        (
            LiturgicalDayId::DayOfMonth(19),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 97",
        ),
        (
            LiturgicalDayId::DayOfMonth(19),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 98",
        ),
        (
            LiturgicalDayId::DayOfMonth(19),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 99",
        ),
        (
            LiturgicalDayId::DayOfMonth(19),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 100",
        ),
        (
            LiturgicalDayId::DayOfMonth(19),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 101",
        ),
        (
            LiturgicalDayId::DayOfMonth(20),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 102",
        ),
        (
            LiturgicalDayId::DayOfMonth(20),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 103",
        ),
        (
            LiturgicalDayId::DayOfMonth(20),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 104",
        ),
        (
            LiturgicalDayId::DayOfMonth(21),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 105",
        ),
        (
            LiturgicalDayId::DayOfMonth(21),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 106",
        ),
        (
            LiturgicalDayId::DayOfMonth(22),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 107",
        ),
        (
            LiturgicalDayId::DayOfMonth(22),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 108",
        ),
        (
            LiturgicalDayId::DayOfMonth(22),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 109",
        ),
        (
            LiturgicalDayId::DayOfMonth(23),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 110",
        ),
        (
            LiturgicalDayId::DayOfMonth(23),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 111",
        ),
        (
            LiturgicalDayId::DayOfMonth(23),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 112",
        ),
        (
            LiturgicalDayId::DayOfMonth(23),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 113",
        ),
        (
            LiturgicalDayId::DayOfMonth(23),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 114",
        ),
        (
            LiturgicalDayId::DayOfMonth(23),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 115",
        ),
        (
            LiturgicalDayId::DayOfMonth(24),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 116",
        ),
        (
            LiturgicalDayId::DayOfMonth(24),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 117",
        ),
        (
            LiturgicalDayId::DayOfMonth(24),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 118",
        ),
        (
            LiturgicalDayId::DayOfMonth(24),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 119:1-8",
        ),
        (
            LiturgicalDayId::DayOfMonth(24),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 119:9-16",
        ),
        (
            LiturgicalDayId::DayOfMonth(24),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 119:17-24",
        ),
        (
            LiturgicalDayId::DayOfMonth(24),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 119:25-32",
        ),
        (
            LiturgicalDayId::DayOfMonth(25),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 119:33-40",
        ),
        (
            LiturgicalDayId::DayOfMonth(25),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 119:41-48",
        ),
        (
            LiturgicalDayId::DayOfMonth(25),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 119:49-56",
        ),
        (
            LiturgicalDayId::DayOfMonth(25),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 119:57-64",
        ),
        (
            LiturgicalDayId::DayOfMonth(25),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 119:65-72",
        ),
        (
            LiturgicalDayId::DayOfMonth(25),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 119:73-80",
        ),
        (
            LiturgicalDayId::DayOfMonth(25),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 119:81-88",
        ),
        (
            LiturgicalDayId::DayOfMonth(25),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 119:89-96",
        ),
        (
            LiturgicalDayId::DayOfMonth(25),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 119:97-104",
        ),
        (
            LiturgicalDayId::DayOfMonth(26),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 119:105-112",
        ),
        (
            LiturgicalDayId::DayOfMonth(26),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 119:113-120",
        ),
        (
            LiturgicalDayId::DayOfMonth(26),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 119:121-128",
        ),
        (
            LiturgicalDayId::DayOfMonth(26),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 119:129-136",
        ),
        (
            LiturgicalDayId::DayOfMonth(26),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 119:137-144",
        ),
        (
            LiturgicalDayId::DayOfMonth(26),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 119:145-152",
        ),
        (
            LiturgicalDayId::DayOfMonth(26),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 119:153-160",
        ),
        (
            LiturgicalDayId::DayOfMonth(26),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 119:161-168",
        ),
        (
            LiturgicalDayId::DayOfMonth(26),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 119:169-176",
        ),
        (
            LiturgicalDayId::DayOfMonth(27),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 120",
        ),
        (
            LiturgicalDayId::DayOfMonth(27),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 121",
        ),
        (
            LiturgicalDayId::DayOfMonth(27),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 122",
        ),
        (
            LiturgicalDayId::DayOfMonth(27),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 123",
        ),
        (
            LiturgicalDayId::DayOfMonth(27),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 124",
        ),
        (
            LiturgicalDayId::DayOfMonth(27),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 125",
        ),
        (
            LiturgicalDayId::DayOfMonth(27),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 126",
        ),
        (
            LiturgicalDayId::DayOfMonth(27),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 127",
        ),
        (
            LiturgicalDayId::DayOfMonth(27),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 128",
        ),
        (
            LiturgicalDayId::DayOfMonth(27),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 129",
        ),
        (
            LiturgicalDayId::DayOfMonth(27),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 130",
        ),
        (
            LiturgicalDayId::DayOfMonth(27),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 131",
        ),
        (
            LiturgicalDayId::DayOfMonth(28),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 132",
        ),
        (
            LiturgicalDayId::DayOfMonth(28),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 133",
        ),
        (
            LiturgicalDayId::DayOfMonth(28),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 134",
        ),
        (
            LiturgicalDayId::DayOfMonth(28),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 135",
        ),
        (
            LiturgicalDayId::DayOfMonth(28),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 136",
        ),
        (
            LiturgicalDayId::DayOfMonth(28),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 137",
        ),
        (
            LiturgicalDayId::DayOfMonth(28),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 138",
        ),
        (
            LiturgicalDayId::DayOfMonth(29),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 139",
        ),
        (
            LiturgicalDayId::DayOfMonth(29),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 140",
        ),
        (
            LiturgicalDayId::DayOfMonth(29),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 141",
        ),
        (
            LiturgicalDayId::DayOfMonth(29),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 142",
        ),
        (
            LiturgicalDayId::DayOfMonth(29),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 143",
        ),
        (
            LiturgicalDayId::DayOfMonth(30),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 144",
        ),
        (
            LiturgicalDayId::DayOfMonth(30),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 145",
        ),
        (
            LiturgicalDayId::DayOfMonth(30),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 146",
        ),
        (
            LiturgicalDayId::DayOfMonth(30),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 147",
        ),
        (
            LiturgicalDayId::DayOfMonth(30),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 148",
        ),
        (
            LiturgicalDayId::DayOfMonth(30),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 149",
        ),
        (
            LiturgicalDayId::DayOfMonth(30),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 150",
        ),
        (
            LiturgicalDayId::DayOfMonth(31),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 144",
        ),
        (
            LiturgicalDayId::DayOfMonth(31),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 145",
        ),
        (
            LiturgicalDayId::DayOfMonth(31),
            Year::Any,
            ReadingType::MorningPsalm,
            "Psalm 146",
        ),
        (
            LiturgicalDayId::DayOfMonth(31),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 147",
        ),
        (
            LiturgicalDayId::DayOfMonth(31),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 148",
        ),
        (
            LiturgicalDayId::DayOfMonth(31),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 149",
        ),
        (
            LiturgicalDayId::DayOfMonth(31),
            Year::Any,
            ReadingType::EveningPsalm,
            "Psalm 150",
        ),
    ],
};
