use crate::{Lectionary, ReadingType};
use calendar::{LiturgicalDayId, Proper, RCLYear, Weekday, Year, YearType};

/// Revised Common Lectionary, Track 1 (Semi-Continuous) for Ordinary Time.
/// Does not include readings that are shared between Track 1 and Track 2,
/// which are found instead in [RCL](crate::lectionary::lectionaries::rcl).
pub const RCL_TRACK_1: Lectionary = Lectionary {
    year_type: YearType::Rcl,
    readings: &[
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper4, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::FirstReading,
            "Genesis 6:9-22; 7:24; 8:14-19",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper4, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::Psalm,
            "Psalm 46",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper4, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::FirstReading,
            "1 Samuel 3:1-10,(11-20)",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper4, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::Psalm,
            "Psalm 139:1-5,12-17",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper4, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::FirstReading,
            "1 Kings 18:20-21,(22-29),30-39",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper4, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::Psalm,
            "Psalm 96",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper5, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::FirstReading,
            "Genesis 12:1-9",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper5, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::Psalm,
            "Psalm 33:1-12",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper5, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::FirstReading,
            "1 Samuel 8:4-11,(12-15),16-20; (11:14-15)",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper5, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::Psalm,
            "Psalm 138",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper5, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::FirstReading,
            "1 Kings 17:8-16,(17-24)",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper5, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::Psalm,
            "Psalm 146",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper6, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::FirstReading,
            "Genesis 18:1-15; (21:1-7)",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper6, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::Psalm,
            "Psalm 116:1,10-17",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper6, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::FirstReading,
            "1 Samuel 15:34-16:13",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper6, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::Psalm,
            "Psalm 20",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper6, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::FirstReading,
            "1 Kings 21:1-10,(11-14),15-21a",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper6, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::Psalm,
            "Psalm 5:1-8",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper7, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::FirstReading,
            "Genesis 21:8-21",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper7, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::Psalm,
            "Psalm 86:1-10,16-17",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper7, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::FirstReading,
            "1 Samuel 17:(1a,4-11,19-23),32-49",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper7, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::FirstReading,
            "1 Samuel 17:57-18:5,10-16",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper7, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::Psalm,
            "Psalm 9:9-20",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper7, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::Psalm,
            "Psalm 133",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper7, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::FirstReading,
            "1 Kings 19:1-4,(5-7),8-15a",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper7, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::Psalm,
            "Psalm 42",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper7, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::Psalm,
            "Psalm 43",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper8, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::FirstReading,
            "Genesis 22:1-14",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper8, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::Psalm,
            "Psalm 13",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper8, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::FirstReading,
            "2 Samuel 1:1,17-27",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper8, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::Psalm,
            "Psalm 130",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper8, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::FirstReading,
            "2 Kings 2:1-2,6-14",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper8, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::Psalm,
            "Psalm 77:1-2,11-20",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper9, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::FirstReading,
            "Genesis 24:34-38,42-49,58-67",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper9, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::Psalm,
            "Psalm 45:11-18",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper9, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::Psalm,
            "Song of Solomon 2:8-13",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper9, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::FirstReading,
            "2 Samuel 5:1-5,9-10",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper9, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::Psalm,
            "Psalm 48",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper9, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::FirstReading,
            "2 Kings 5:1-14",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper9, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::Psalm,
            "Psalm 30",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper10, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::FirstReading,
            "Genesis 25:19-34",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper10, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::Psalm,
            "Psalm 119:105-112",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper10, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::FirstReading,
            "2 Samuel 6:1-5,12b-19",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper10, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::Psalm,
            "Psalm 24",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper10, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::FirstReading,
            "Amos 7:7-17",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper10, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::Psalm,
            "Psalm 82",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper11, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::FirstReading,
            "Genesis 28:10-19a",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper11, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::Psalm,
            "Psalm 139:1-11,22-23",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper11, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::Psalm,
            "Wisdom of Solomon 12:13,16-19",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper11, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::FirstReading,
            "2 Samuel 7:1-14a",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper11, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::Psalm,
            "Psalm 89:20-37",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper11, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::FirstReading,
            "Amos 8:1-12",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper11, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::Psalm,
            "Psalm 52",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper12, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::FirstReading,
            "Genesis 29:15-28",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper12, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::Psalm,
            "Psalm 105:1-11,45b",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper12, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::Psalm,
            "Psalm 128",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper12, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::FirstReading,
            "2 Samuel 11:1-15",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper12, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::Psalm,
            "Psalm 14",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper12, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::FirstReading,
            "Hosea 1:2-10",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper12, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::Psalm,
            "Psalm 85",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper13, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::FirstReading,
            "Genesis 32:22-31",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper13, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::Psalm,
            "Psalm 17:1-7,16",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper13, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::FirstReading,
            "2 Samuel 11:26-12:13a",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper13, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::Psalm,
            "Psalm 51:1-13",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper13, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::FirstReading,
            "Hosea 11:1-11",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper13, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::Psalm,
            "Psalm 107:1-9,43",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper14, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::FirstReading,
            "Genesis 37:1-4,12-28",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper14, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::Psalm,
            "Psalm 105:1-6,16-22,45b",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper14, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::FirstReading,
            "2 Samuel 18:5-9,15,31-33",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper14, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::Psalm,
            "Psalm 130",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper14, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::FirstReading,
            "Isaiah 1:1,10-20",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper14, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::Psalm,
            "Psalm 50:1-8,23-24",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper15, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::FirstReading,
            "Genesis 45:1-15",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper15, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::Psalm,
            "Psalm 133",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper15, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::FirstReading,
            "1 Kings 2:10-12; 3:3-14",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper15, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::Psalm,
            "Psalm 111",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper15, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::FirstReading,
            "Isaiah 5:1-7",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper15, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::Psalm,
            "Psalm 80:1-2,8-18",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper16, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::FirstReading,
            "Exodus 1:8-2:10",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper16, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::Psalm,
            "Psalm 124",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper16, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::FirstReading,
            "1 Kings 8:(1,6,10-11),22-30,41-43",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper16, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::Psalm,
            "Psalm 84",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper16, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::FirstReading,
            "Jeremiah 1:4-10",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper16, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::Psalm,
            "Psalm 71:1-6",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper17, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::FirstReading,
            "Exodus 3:1-15",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper17, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::Psalm,
            "Psalm 105:1-6,23-26,45c",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper17, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::FirstReading,
            "Song of Solomon 2:8-13",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper17, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::Psalm,
            "Psalm 45:1-2,7-10",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper17, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::FirstReading,
            "Jeremiah 2:4-13",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper17, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::Psalm,
            "Psalm 81:1,10-16",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper18, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::FirstReading,
            "Exodus 12:1-14",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper18, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::Psalm,
            "Psalm 149",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper18, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::FirstReading,
            "Proverbs 22:1-2,8-9,22-23",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper18, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::Psalm,
            "Psalm 125",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper18, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::FirstReading,
            "Jeremiah 18:1-11",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper18, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::Psalm,
            "Psalm 139:1-5,12-17",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper19, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::FirstReading,
            "Exodus 14:19-31",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper19, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::Psalm,
            "Psalm 114",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper19, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::Psalm,
            "Exodus 15:1b-11,20-21",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper19, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::FirstReading,
            "Proverbs 1:20-33",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper19, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::Psalm,
            "Psalm 19",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper19, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::Psalm,
            "Wisdom of Solomon 7:26-8:1",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper19, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::FirstReading,
            "Jeremiah 4:11-12,22-28",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper19, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::Psalm,
            "Psalm 14",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper20, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::FirstReading,
            "Exodus 16:2-15",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper20, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::Psalm,
            "Psalm 105:1-6,37-45",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper20, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::FirstReading,
            "Proverbs 31:10-31",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper20, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::Psalm,
            "Psalm 1",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper20, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::FirstReading,
            "Jeremiah 8:18-9:1",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper20, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::Psalm,
            "Psalm 79:1-9",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper21, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::FirstReading,
            "Exodus 17:1-7",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper21, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::Psalm,
            "Psalm 78:1-4,12-16",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper21, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::FirstReading,
            "Esther 7:1-6,9-10; 9:20-22",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper21, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::Psalm,
            "Psalm 124",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper21, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::FirstReading,
            "Jeremiah 32:1-3a,6-15",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper21, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::Psalm,
            "Psalm 91:1-6,14-16",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper22, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::FirstReading,
            "Exodus 20:1-4,7-9,12-20",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper22, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::Psalm,
            "Psalm 19",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper22, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::FirstReading,
            "Job 1:1; 2:1-10",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper22, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::Psalm,
            "Psalm 26",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper22, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::FirstReading,
            "Lamentations 1:1-6",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper22, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::Psalm,
            "Lamentations 3:19-26",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper22, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::Psalm,
            "Psalm 137",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper23, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::FirstReading,
            "Exodus 32:1-14",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper23, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::Psalm,
            "Psalm 106:1-6,19-23",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper23, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::FirstReading,
            "Job 23:1-9,16-17",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper23, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::Psalm,
            "Psalm 22:1-15",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper23, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::FirstReading,
            "Jeremiah 29:1,4-7",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper23, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::Psalm,
            "Psalm 66:1-11",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper24, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::FirstReading,
            "Exodus 33:12-23",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper24, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::Psalm,
            "Psalm 99",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper24, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::FirstReading,
            "Job 38:1-7,(34-41)",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper24, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::Psalm,
            "Psalm 104:1-9,25,37b",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper24, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::FirstReading,
            "Jeremiah 31:27-34",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper24, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::Psalm,
            "Psalm 119:97-104",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper25, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::FirstReading,
            "Deuteronomy 34:1-12",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper25, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::Psalm,
            "Psalm 90:1-6,13-17",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper25, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::FirstReading,
            "Job 42:1-6,10-17",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper25, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::Psalm,
            "Psalm 34:1-8,(19-22)",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper25, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::FirstReading,
            "Joel 2:23-32",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper25, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::Psalm,
            "Psalm 65",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper26, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::FirstReading,
            "Joshua 3:7-17",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper26, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::Psalm,
            "Psalm 107:1-7,33-37",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper26, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::FirstReading,
            "Ruth 1:1-18",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper26, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::Psalm,
            "Psalm 146",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper26, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::FirstReading,
            "Habakkuk 1:1-4; 2:1-4",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper26, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::Psalm,
            "Psalm 119:137-144",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper27, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::FirstReading,
            "Joshua 24:1-3a,14-25",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper27, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::Psalm,
            "Psalm 78:1-7",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper27, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::FirstReading,
            "Ruth 3:1-5; 4:13-17",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper27, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::Psalm,
            "Psalm 127",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper27, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::FirstReading,
            "Haggai 1:15b-2:9",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper27, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::Psalm,
            "Psalm 145:1-5,18-22",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper27, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::Psalm,
            "Psalm 98",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper28, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::FirstReading,
            "Judges 4:1-7",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper28, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::Psalm,
            "Psalm 123",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper28, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::FirstReading,
            "1 Samuel 1:4-20",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper28, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::Psalm,
            "1 Samuel 2:1-10",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper28, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::FirstReading,
            "Isaiah 65:17-25",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper28, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::Psalm,
            "canticle-9",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper29, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::FirstReading,
            "Ezekiel 34:11-16,20-24",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper29, Weekday::Sun),
            Year::Rcl(RCLYear::A),
            ReadingType::Psalm,
            "Psalm 100",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper29, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::FirstReading,
            "2 Samuel 23:1-7",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper29, Weekday::Sun),
            Year::Rcl(RCLYear::B),
            ReadingType::Psalm,
            "Psalm 132:1-13,(14-19)",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper29, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::FirstReading,
            "Jeremiah 23:1-6",
        ),
        (
            LiturgicalDayId::ProperAndDay(Proper::Proper29, Weekday::Sun),
            Year::Rcl(RCLYear::C),
            ReadingType::Psalm,
            "canticle-16",
        ),
    ],
};
