[workspace]
members = [
	"app",
	"client/calendar",
	"client/daily_office",
	"client/document",
	"client/hymn",
	"client/hymnal",
	"server",
]

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'