use crate::{Hymn, HymnNumber, Hymnal, Hymnals};
use lazy_static::lazy_static;

#[cfg(test)]
mod tests {
    use crate::LEVAS;

    #[test]
    fn contains_all_consecutive_hymn_numbers() {
        let mut last_number = 0;
        for hymn in &LEVAS.hymns {
            let num = match hymn.number {
                crate::HymnNumber::S(_) => panic!(), // no S section in WLP
                crate::HymnNumber::H(n) => n,
            };
            assert_eq!(num, last_number + 1);
            last_number = num;
        }
    }
}

lazy_static! {
	pub static ref LEVAS: Hymnal = Hymnal {
		id: Hymnals::LEVAS,
		title: "Lift Every Voice and Sing II".to_string(),
		subtitle: "An African American Hymnal".to_string(),
		copyright: "Copyright © 1993 by The Church Pension Fund".to_string(),
		year: 1993,
		hymns: vec![
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(1),
				title: "Lift ev’ry voice and sing".to_string(),
				tune: "[Lift ev’ry voice and sing]".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(2),
				title: "Oh thou that tellest good tidings to Zion".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(3),
				title: "I know my robe’s gonna fit me well".to_string(),
				tune: "[I know my robe’s gonna fit me well]".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(4),
				title: "Oh! rise up children, get your crown".to_string(),
				tune: "[Oh! Rise up children, get your crown]".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(5),
				title: "Chariot rode on the mountaintop".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(6),
				title: "Christ is coming: Prepare the way".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(7),
				title: "John said that Jerusalem was four-square".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(8),
				title: "Deep river, my home is over Jordan".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(9),
				title: "On Jordan’s stormy banks I stand".to_string(),
				tune: "[On Jordan’s stormy banks I stand]".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(10),
				title: "There’s three gates in-a the East".to_string(),
				tune: "[There’s three gates in-a the East]".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(11),
				title: "Make straight in the desert a highway for our God".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(12),
				title: "Come, we that love the Lord".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(13),
				title: "You’ll hear the trumpet sound".to_string(),
				tune: "[You’ll hear the trumpet sound]".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(14),
				title: "Soon and very soon we are goin’ to see the King".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(15),
				title: "Hebrew children in de fiery furnace".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(16),
				title: "Lord, You have searched my heart".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(17),
				title: "Church gettin’ higher! Rockin’ Jerusalem!".to_string(),
				tune: "[Church gettin’ higher! Rockin’ Jerusalem!]".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(18),
				title: "I looked over Jordan, and what did I see".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(19),
				title: "I’m just a poor wayfaring stranger".to_string(),
				tune: "[I’m just a poor wayfaring stranger]".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(20),
				title: "Sing the wondrous love of Jesus".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(21),
				title: "While shepherds kept their watching".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(22),
				title: "Mary borned a baby, Mary borned a baby".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(23),
				title: "Jesus came to earth from glory".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(24),
				title: "There’s a star in the east on Christmas morn".to_string(),
				tune: "[There’s a star in the east on Christmas morn]".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(25),
				title: "What shall we call Him".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(26),
				title: "Silent night, holy night".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(27),
				title: "Away in a manger, no crib for a bed".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(28),
				title: "Down at the cross where my Savior died".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(29),
				title: "Jesus, keep me near the cross".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(30),
				title: "Alas! And did my Savior bleed".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(31),
				title: "King of my life I crown thee now".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(32),
				title: "Ev’ry time I think about Jesus".to_string(),
				tune: "[Ev’ry time I think about Jesus]".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(33),
				title: "They crucified my Lord, and He never said a mumbalin’ word".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(34),
				title: "When on the cross of Calv’ry".to_string(),
				tune: "[When on the cross of Calv’ry]".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(35),
				title: "O how He loves you and me".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(36),
				title: "O sacred head, sore wounded".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(37),
				title: "Were you there when they crucified my Lord?".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(38),
				title: "On a hill far away stood an old rugged cross".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(39),
				title: "There is a fountain filled with blood".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(40),
				title: "They crucified my Savior and nailed him to the tree".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(41),
				title: "Christ has arisen, Alleluia".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(42),
				title: "I serve a risen Savior".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(43),
				title: "God sent His Son, they called Him Jesus".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(44),
				title: "Born in bondage, born in shackles".to_string(),
				tune: "LAUDA ANIMA".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(45),
				title: "O Monica, blest mother".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(46),
				title: "Holy God, you raise up prophets".to_string(),
				tune: "MARTIN’S SONG".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(47),
				title: "O Cyprian, convert to the faith".to_string(),
				tune: "ROCKINGHAM".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(48),
				title: "In Afric’s northern coastland".to_string(),
				tune: "LANCASHIRE".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(49),
				title: "O Jesus scourged, derided, mocked".to_string(),
				tune: "NEW BRITAIN".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(50),
				title: "The angel said to Philip".to_string(),
				tune: "NYLAND".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(51),
				title: "Salamu Maria, ee mama ( Hail Mary, Oh mother)".to_string(),
				tune: "[Salamu Maria, ee mama]".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(52),
				title: "He is the source of all my joy".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(53),
				title: "Glory to God in the highest".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(54),
				title: "Nearer, my God, to Thee".to_string(),
				tune: "BETHANY".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(55),
				title: "In God we trust, with all our heart and soul".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(56),
				title: "Praise God from whom all blessings flow".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(57),
				title: "Oh Lord, How perfect is your name".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(58),
				title: "The Lord is my light and my salvation".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(59),
				title: "I trust in God wherever I may be".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(60),
				title: "O Lord my God, when I in awesome wonder".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(61),
				title: "The right hand of God is writing in our land".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(62),
				title: "In Christ there is no East or West".to_string(),
				tune: "MCKEE".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(63),
				title: "Glorious is the Name of Jesus".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(64),
				title: "I love to tell the story".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(65),
				title: "Bless the Lord, O my soul".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(66),
				title: "I must tell Jesus all of my trials".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(67),
				title: "I love the Lord, He heard my cry".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(68),
				title: "Some folk would rather have houses and land".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(69),
				title: "I come to the garden alone".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(70),
				title: "I want Jesus to walk with me".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(71),
				title: "In times like these you need a Savior".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(72),
				title: "I am weak but thou art strong".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(73),
				title: "This world’s a wilderness of woe".to_string(),
				tune: "[This world’s a wilderness of woe]".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(74),
				title: "Kneels at the feet of his friends".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(75),
				title: "Jesu, Joy of our desiring".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(76),
				title: "Jesus, Jesus, Jesus in the morning".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(77),
				title: "Jesus is all the world to me".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(78),
				title: "Blessed be the name! Blessed be the name!".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(79),
				title: "Jesus, lover of my soul".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(80),
				title: "Jesus, Savior, pilot me".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(81),
				title: "Jesus, we want to meet".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(82),
				title: "Just when I need Him".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(83),
				title: "I once was lost in sin".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(84),
				title: "That Gospel train is comin’".to_string(),
				tune: "[That Gospel train is comin’]".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(85),
				title: "Let all that is within me cry, “Holy!”".to_string(),
				tune: "[Let all that is within me cry, “Holy!”]".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(86),
				title: "If your life in days gone by".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(87),
				title: "More love to thee, O Christ".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(88),
				title: "My faith looks up to thee".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(89),
				title: "My Jesus, I love thee, I know thou art mine".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(90),
				title: "There’s not a friend like the lowly Jesus".to_string(),
				tune: "[There’s not a friend like the lowly Jesus]".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(91),
				title: "In the morning when I rise".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(92),
				title: "Nothing between my soul and the Savior".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(93),
				title: "To Him alone who does mighty wonders".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(94),
				title: "O holy Savior! friend unseen".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(95),
				title: "There is a name I love to hear".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(96),
				title: "He built his throne up in the air".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(97),
				title: "King Jesus rides a milk-white horse".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(98),
				title: "Praise Him! Praise Him! Praise Him! Praise Him!".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(99),
				title: "My hope is built on nothing less".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(100),
				title: "Knocks like Jesus".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(101),
				title: "Softly and tenderly Jesus is calling".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(102),
				title: "My Jesus came to earth from glory".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(103),
				title: "My Lord calls me".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(104),
				title: "The Lord is my Shepherd, no want shall I know".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(105),
				title: "I’m so glad Jesus lifted me".to_string(),
				tune: "[I’m so glad Jesus lifted me]".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(106),
				title: "Precious Lord, take my hand".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(107),
				title: "Jesus, Jesus, Jesus!".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(108),
				title: "’Tis so sweet to trust in Jesus".to_string(),
				tune: "[’Tis so sweet to trust in Jesus]".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(109),
				title: "What a friend we have in Jesus".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(110),
				title: "My Savior spoke these words so sweet".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(111),
				title: "Come, Thou fount of every blessing".to_string(),
				tune: "NETTLETON".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(112),
				title: "Come, Holy Ghost, Creator blest".to_string(),
				tune: "LAMBILLOTTE".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(113),
				title: "How like a gentle spirit deep within".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(114),
				title: "Upon the mountain my Lord spoke".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(115),
				title: "Spirit of the Living God".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(116),
				title: "While I’m working Lord in your vineyard here".to_string(),
				tune: "[While I’m working Lord in your vineyard here]".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(117),
				title: "I’m goin’-a sing when the Spirit says sing".to_string(),
				tune: "[I’m goin’-a sing when the Spirit says sing]".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(118),
				title: "Oh, let the Son of God enfold you".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(119),
				title: "Spirit of God, descend upon my heart".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(120),
				title: "There’s a sweet, sweet Spirit in this place".to_string(),
				tune: "[There’s a sweet, sweet Spirit in this place]".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(121),
				title: "Baptized in water, sealed by the Spirit".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(122),
				title: "Thou my everlasting portion".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(123),
				title: "Sometimes I’m up, sometimes I’m down".to_string(),
				tune: "[Sometimes I’m up, sometimes I’m down]".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(124),
				title: "I’m not asking for the riches of the land".to_string(),
				tune: "[I’m not asking for the riches of the land]".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(125),
				title: "Fix me for my long white robe".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(126),
				title: "Hark! the voice of Jesus calling".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(127),
				title: "Po’ sinner, do you love Jesus?".to_string(),
				tune: "[Po’ sinner, do you love Jesus?]".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(128),
				title: "Hush, hush, somebody’s callin’ my name".to_string(),
				tune: "[Hush, hush, somebody’s callin’ my name]".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(129),
				title: "I am thine, O Lord, I have heard thy voice".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(130),
				title: "Glory, glory, hallelujah! ".to_string(),
				tune: "[Glory, glory, hallelujah!]".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(131),
				title: "Did ever you see the like before".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(132),
				title: "Have you got good religion?".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(133),
				title: "All to Jesus I surrender".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(134),
				title: "Take me to the water".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(135),
				title: "You have longed for sweet peace".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(136),
				title: "I have decided to follow Jesus".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(137),
				title: "Just as I am, without one plea".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(138),
				title: "Lord, I want to be a Christian".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(139),
				title: "Pass me not, O gentle Savior".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(140),
				title: "Some folks want treasures of silver and gold".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(141),
				title: "Shall we gather at the river".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(142),
				title: "Sign me up for the Christian jubilee".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(143),
				title: "See that host all dressed in white".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(144),
				title: "I can hear my Savior calling".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(145),
				title: "Have thine own way, Lord!".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(146),
				title: "Break thou the bread of life".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(147),
				title: "Come, ye disconsolate, where’er ye languish".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(148),
				title: "I’m a-going to eat at the welcome table".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(149),
				title: "In remembrance of me, eat this bread".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(150),
				title: "I am the Bread that came down from heaven".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(151),
				title: "Gentile or Jew, servant or free".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(152),
				title: "Let us break bread together on our knees".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(153),
				title: "Lord I have seen thy salvation".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(154),
				title: "I will bless the Lord at all times".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(155),
				title: "This is my body given up for you".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(156),
				title: "Come to me, Ye who are hard oppressed".to_string(),
				tune: "[“Come to me, Ye who are hard oppressed]".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(157),
				title: "We praise thee, O God".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(158),
				title: "Out in the highways and byways of life".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(159),
				title: "How to reach the masses, those of ev’ry birth".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(160),
				title: "This little light of mine".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(161),
				title: "“Go preach my gospel,” saith the Lord".to_string(),
				tune: "[“Go preach my gospel,” saith the Lord]".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(162),
				title: "Come by here Lord".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(163),
				title: "No harm have I done you on my knees".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(164),
				title: "Do Lord, do Lord".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(165),
				title: "I’m pressing on the upward way".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(166),
				title: "Lord, my soul is thirsting for a blessing today".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(167),
				title: "Lord I hear of show’rs of blessings".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(168),
				title: "I have a Savior, He’s pleading in glory".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(169),
				title: "Sometimes I feel like a motherless chile".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(170),
				title: "Yield not to temptation".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(171),
				title: "In de valley".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(172),
				title: "Brother will you pray for me?".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(173),
				title: "Lord, I want to live for thee".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(174),
				title: "Let the heav’n light shine on me".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(175),
				title: "Sometimes I’m up, sometimes I’m down".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(176),
				title: "If I have wounded any soul today".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(177),
				title: "Not my brother, not my sister, but it’s me, O Lord".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(178),
				title: "Sweet hour of prayer, sweet hour of prayer".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(179),
				title: "Remember me, Remember me".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(180),
				title: "I got a robe up in-a that kingdom".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(181),
				title: "Amazing grace! how sweet the sound".to_string(),
				tune: "NEW BRITAIN".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(182),
				title: "He delivered Daniel from the lion’s den".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(183),
				title: "Be not dismayed whate’er betide".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(184),
				title: "Blessed assurance, Jesus is mine!".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(185),
				title: "Joys are flowing like a river".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(186),
				title: "I can do all things through Christ who strengthens me".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(187),
				title: "Tempted and tried we’re oft made to wonder".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(188),
				title: "When peace, like a river, attendeth my way".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(189),
				title: "Great is thy faithfulness, O God my Father".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(190),
				title: "If when you give the best of your service".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(191),
				title: "Why should I feel discouraged".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(192),
				title: "I need thee ev’ry hour".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(193),
				title: "I will trust in the Lord".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(194),
				title: "I am weak and I need thy strength and power".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(195),
				title: "I’ve been ’buked an’ I’ve been scorned".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(196),
				title: "What a fellowship, what a joy divine".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(197),
				title: "If the world from you withhold".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(198),
				title: "I was sinking deep in sin".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(199),
				title: "I don’t feel no ways tired".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(200),
				title: "When the storms of life are raging".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(201),
				title: "I’ve got peace like a river".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(202),
				title: "The church of God must now prevail".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(203),
				title: "Sometimes I feel discouraged".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(204),
				title: "When waves of affliction sweep over the soul".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(205),
				title: "When we walk with the Lord".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(206),
				title: "We walk by faith, and not by sight".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(207),
				title: "We are often tossed and driv’n".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(208),
				title: "Don’t be discouraged when trouble’s in your life".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(209),
				title: "There are some things I may not know".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(210),
				title: "Goin’ to lay down my sword and shield".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(211),
				title: "Little David was a shepherd boy".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(212),
				title: "Born to rule the earth".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(213),
				title: "Children of the heav’nly Father".to_string(),
				tune: "[Children of the heav’nly Father]".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(214),
				title: "God is so good".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(215),
				title: "God, our Father, we adore you, magnify you".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(216),
				title: "In my life, Lord, be glorified, be glorified".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(217),
				title: "He’s got the whole world in His hand".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(218),
				title: "Jesus loves me! this I know".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(219),
				title: "This is the day, this the day".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(220),
				title: "We are climbing Jacob’s ladder".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(221),
				title: "This little light of mine, I’m gonna let it shine".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(222),
				title: "Jesus loves the little children".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(223),
				title: "You may talk about the man of Gideon".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(224),
				title: "Better min’, my sister".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(225),
				title: "Oh, freedom! Oh, freedom".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(226),
				title: "Mine eyes have seen the glory".to_string(),
				tune: "BATTLE HYMN OF THE REPUBLIC".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(227),
				title: "We shall overcome".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(228),
				title: "When Israel was in Egypt’s land".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(229),
				title: "Martin’s dream for all of us so set his soul afire".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(230),
				title: "’Way down yonder in the graveyard walk".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(231),
				title: "The Lord bless you and keep you".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(232),
				title: "Thank you, Lord".to_string(),
				tune: "[Thank you, Lord, Thank you, Lord]".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(233),
				title: "See the little baby".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(234),
				title: "God be with you, God be with you".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(235),
				title: "Lord have mercy, Lord have mercy".to_string(),
				tune: "[Lord have mercy, Lord have mercy, Lord have mercy]".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(236),
				title: "Lord, have mercy".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(237),
				title: "Lord, have mercy".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(238),
				title: "Lord, have mercy".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(239),
				title: "Kyrie eleison".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(240),
				title: "Lord, have mercy".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(241),
				title: "Glory to God in the highest".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(242),
				title: "Glory to God in the highest".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(243),
				title: "Glory, Glory, hallelujah".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(244),
				title: "I will praise the Father".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(245),
				title: "We have come into His house".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(246),
				title: "Praise, praise, honor and glory".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(247),
				title: "With all our heart and with all our mind".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(248),
				title: "Let us pray for the Church and for the world".to_string(),
				tune: "[Let us pray for the Church and for the world] (Pulkingham)".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(249),
				title: "Hear our prayer, O Lord".to_string(),
				tune: "[Hear our prayer, O Lord, hear our prayer, O Lord]".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(250),
				title: "O Lord, Hear us, we pray".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(251),
				title: "Lead me, Lord, lead me in thy righteousness".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(252),
				title: "Holy, holy, holy Lord, God of power and might".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(253),
				title: "Holy, holy, holy Lord, God of power and might".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(254),
				title: "Holy, holy, holy Lord, God of power and might".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(255),
				title: "Holy, holy, holy, holy, holy Lord God of hosts".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(256),
				title: "Holy, holy, holy Lord, God of pow’r and might".to_string(),
				tune: "[Holy, holy, holy Lord, God of pow’r and might]".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(257),
				title: "Therefore we proclaim the mystery of faith".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(258),
				title: "Christ has died".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(259),
				title: "Christ has died".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(260),
				title: "We remember His death".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(261),
				title: "Amen".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(262),
				title: "Amen".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(263),
				title: "Our Father in heaven".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(264),
				title: "Our Father, which art in heaven".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(265),
				title: "Our Father in heaven".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(266),
				title: "Our Father in heaven".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(267),
				title: "Our Father, who art in heaven".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(268),
				title: "Christ our passover is sacrificed for us".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(269),
				title: "Lamb of God, you take away the sins of the world".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(270),
				title: "Lamb of God, you take away the sins of the world".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(271),
				title: "Lamb of God, you take away the sins of the world".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(272),
				title: "Do this in remembrance of me".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(273),
				title: "His love, His love, His love is everlasting".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(274),
				title: "The Lord is gracious and full of compassion".to_string(),
				tune: "[I will praise your name forever]".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(275),
				title: "Lord, send out your spirit!".to_string(),
				tune: "[Lord, send out your spirit]".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(276),
				title: "My God, My God, why have you abandoned me?".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(277),
				title: "The Lord is my light and my salvation".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(278),
				title: "Serve the Lord with gladness, alleluia".to_string(),
				tune: "".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(279),
				title: "The Lord is my shepherd; there is nothing I shall want".to_string(),
				tune: "[The Lord is my shepherd]".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(280),
				title: "To you, O Lord, I lift up my soul".to_string(),
				tune: "[To you, O Lord, I lift up my soul".to_string(),
			},
			Hymn {
				source: Hymnals::LEVAS,
				number: HymnNumber::H(281),
				title: "Bless, O Lord, our country, Africa ".to_string(),
				tune: "[Bless, O Lord, our country, Africa]".to_string(),
			},
		],
	};
}
