use crate::{Hymn, HymnNumber, Hymnal, Hymnals};

#[cfg(test)]
mod tests {
    use crate::LEVAS;

    #[test]
    fn contains_all_consecutive_hymn_numbers() {
        let mut last_number = 0;
        for hymn in LEVAS.hymns {
            let num = match hymn.number {
                crate::HymnNumber::S(_) => panic!(), // no S section in WLP
                crate::HymnNumber::H(n) => n,
            };
            assert_eq!(num, last_number + 1);
            last_number = num;
        }
    }
}

pub const LEVAS: Hymnal = Hymnal {
    title: "Lift Every Voice and Sing II",
    subtitle: "An African American Hymnal",
    copyright: "Copyright © 1993 by The Church Pension Fund",
    year: 1993,
    hymns: &[
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(1),
            title: "Lift ev’ry voice and sing",
            tune: "[Lift ev’ry voice and sing]",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(2),
            title: "Oh thou that tellest good tidings to Zion",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(3),
            title: "I know my robe’s gonna fit me well",
            tune: "[I know my robe’s gonna fit me well]",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(4),
            title: "Oh! rise up children, get your crown",
            tune: "[Oh! Rise up children, get your crown]",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(5),
            title: "Chariot rode on the mountaintop",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(6),
            title: "Christ is coming: Prepare the way",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(7),
            title: "John said that Jerusalem was four-square",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(8),
            title: "Deep river, my home is over Jordan",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(9),
            title: "On Jordan’s stormy banks I stand",
            tune: "[On Jordan’s stormy banks I stand]",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(10),
            title: "There’s three gates in-a the East",
            tune: "[There’s three gates in-a the East]",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(11),
            title: "Make straight in the desert a highway for our God",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(12),
            title: "Come, we that love the Lord",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(13),
            title: "You’ll hear the trumpet sound",
            tune: "[You’ll hear the trumpet sound]",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(14),
            title: "Soon and very soon we are goin’ to see the King",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(15),
            title: "Hebrew children in de fiery furnace",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(16),
            title: "Lord, You have searched my heart",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(17),
            title: "Church gettin’ higher! Rockin’ Jerusalem!",
            tune: "[Church gettin’ higher! Rockin’ Jerusalem!]",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(18),
            title: "I looked over Jordan, and what did I see",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(19),
            title: "I’m just a poor wayfaring stranger",
            tune: "[I’m just a poor wayfaring stranger]",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(20),
            title: "Sing the wondrous love of Jesus",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(21),
            title: "While shepherds kept their watching",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(22),
            title: "Mary borned a baby, Mary borned a baby",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(23),
            title: "Jesus came to earth from glory",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(24),
            title: "There’s a star in the east on Christmas morn",
            tune: "[There’s a star in the east on Christmas morn]",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(25),
            title: "What shall we call Him",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(26),
            title: "Silent night, holy night",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(27),
            title: "Away in a manger, no crib for a bed",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(28),
            title: "Down at the cross where my Savior died",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(29),
            title: "Jesus, keep me near the cross",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(30),
            title: "Alas! And did my Savior bleed",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(31),
            title: "King of my life I crown thee now",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(32),
            title: "Ev’ry time I think about Jesus",
            tune: "[Ev’ry time I think about Jesus]",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(33),
            title: "They crucified my Lord, and He never said a mumbalin’ word",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(34),
            title: "When on the cross of Calv’ry",
            tune: "[When on the cross of Calv’ry]",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(35),
            title: "O how He loves you and me",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(36),
            title: "O sacred head, sore wounded",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(37),
            title: "Were you there when they crucified my Lord?",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(38),
            title: "On a hill far away stood an old rugged cross",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(39),
            title: "There is a fountain filled with blood",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(40),
            title: "They crucified my Savior and nailed him to the tree",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(41),
            title: "Christ has arisen, Alleluia",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(42),
            title: "I serve a risen Savior",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(43),
            title: "God sent His Son, they called Him Jesus",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(44),
            title: "Born in bondage, born in shackles",
            tune: "LAUDA ANIMA",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(45),
            title: "O Monica, blest mother",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(46),
            title: "Holy God, you raise up prophets",
            tune: "MARTIN’S SONG",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(47),
            title: "O Cyprian, convert to the faith",
            tune: "ROCKINGHAM",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(48),
            title: "In Afric’s northern coastland",
            tune: "LANCASHIRE",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(49),
            title: "O Jesus scourged, derided, mocked",
            tune: "NEW BRITAIN",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(50),
            title: "The angel said to Philip",
            tune: "NYLAND",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(51),
            title: "Salamu Maria, ee mama ( Hail Mary, Oh mother)",
            tune: "[Salamu Maria, ee mama]",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(52),
            title: "He is the source of all my joy",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(53),
            title: "Glory to God in the highest",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(54),
            title: "Nearer, my God, to Thee",
            tune: "BETHANY",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(55),
            title: "In God we trust, with all our heart and soul",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(56),
            title: "Praise God from whom all blessings flow",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(57),
            title: "Oh Lord, How perfect is your name",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(58),
            title: "The Lord is my light and my salvation",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(59),
            title: "I trust in God wherever I may be",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(60),
            title: "O Lord my God, when I in awesome wonder",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(61),
            title: "The right hand of God is writing in our land",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(62),
            title: "In Christ there is no East or West",
            tune: "MCKEE",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(63),
            title: "Glorious is the Name of Jesus",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(64),
            title: "I love to tell the story",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(65),
            title: "Bless the Lord, O my soul",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(66),
            title: "I must tell Jesus all of my trials",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(67),
            title: "I love the Lord, He heard my cry",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(68),
            title: "Some folk would rather have houses and land",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(69),
            title: "I come to the garden alone",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(70),
            title: "I want Jesus to walk with me",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(71),
            title: "In times like these you need a Savior",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(72),
            title: "I am weak but thou art strong",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(73),
            title: "This world’s a wilderness of woe",
            tune: "[This world’s a wilderness of woe]",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(74),
            title: "Kneels at the feet of his friends",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(75),
            title: "Jesu, Joy of our desiring",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(76),
            title: "Jesus, Jesus, Jesus in the morning",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(77),
            title: "Jesus is all the world to me",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(78),
            title: "Blessed be the name! Blessed be the name!",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(79),
            title: "Jesus, lover of my soul",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(80),
            title: "Jesus, Savior, pilot me",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(81),
            title: "Jesus, we want to meet",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(82),
            title: "Just when I need Him",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(83),
            title: "I once was lost in sin",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(84),
            title: "That Gospel train is comin’",
            tune: "[That Gospel train is comin’]",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(85),
            title: "Let all that is within me cry, “Holy!”",
            tune: "[Let all that is within me cry, “Holy!”]",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(86),
            title: "If your life in days gone by",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(87),
            title: "More love to thee, O Christ",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(88),
            title: "My faith looks up to thee",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(89),
            title: "My Jesus, I love thee, I know thou art mine",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(90),
            title: "There’s not a friend like the lowly Jesus",
            tune: "[There’s not a friend like the lowly Jesus]",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(91),
            title: "In the morning when I rise",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(92),
            title: "Nothing between my soul and the Savior",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(93),
            title: "To Him alone who does mighty wonders",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(94),
            title: "O holy Savior! friend unseen",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(95),
            title: "There is a name I love to hear",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(96),
            title: "He built his throne up in the air",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(97),
            title: "King Jesus rides a milk-white horse",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(98),
            title: "Praise Him! Praise Him! Praise Him! Praise Him!",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(99),
            title: "My hope is built on nothing less",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(100),
            title: "Knocks like Jesus",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(101),
            title: "Softly and tenderly Jesus is calling",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(102),
            title: "My Jesus came to earth from glory",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(103),
            title: "My Lord calls me",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(104),
            title: "The Lord is my Shepherd, no want shall I know",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(105),
            title: "I’m so glad Jesus lifted me",
            tune: "[I’m so glad Jesus lifted me]",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(106),
            title: "Precious Lord, take my hand",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(107),
            title: "Jesus, Jesus, Jesus!",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(108),
            title: "’Tis so sweet to trust in Jesus",
            tune: "[’Tis so sweet to trust in Jesus]",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(109),
            title: "What a friend we have in Jesus",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(110),
            title: "My Savior spoke these words so sweet",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(111),
            title: "Come, Thou fount of every blessing",
            tune: "NETTLETON",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(112),
            title: "Come, Holy Ghost, Creator blest",
            tune: "LAMBILLOTTE",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(113),
            title: "How like a gentle spirit deep within",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(114),
            title: "Upon the mountain my Lord spoke",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(115),
            title: "Spirit of the Living God",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(116),
            title: "While I’m working Lord in your vineyard here",
            tune: "[While I’m working Lord in your vineyard here]",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(117),
            title: "I’m goin’-a sing when the Spirit says sing",
            tune: "[I’m goin’-a sing when the Spirit says sing]",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(118),
            title: "Oh, let the Son of God enfold you",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(119),
            title: "Spirit of God, descend upon my heart",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(120),
            title: "There’s a sweet, sweet Spirit in this place",
            tune: "[There’s a sweet, sweet Spirit in this place]",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(121),
            title: "Baptized in water, sealed by the Spirit",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(122),
            title: "Thou my everlasting portion",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(123),
            title: "Sometimes I’m up, sometimes I’m down",
            tune: "[Sometimes I’m up, sometimes I’m down]",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(124),
            title: "I’m not asking for the riches of the land",
            tune: "[I’m not asking for the riches of the land]",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(125),
            title: "Fix me for my long white robe",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(126),
            title: "Hark! the voice of Jesus calling",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(127),
            title: "Po’ sinner, do you love Jesus?",
            tune: "[Po’ sinner, do you love Jesus?]",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(128),
            title: "Hush, hush, somebody’s callin’ my name",
            tune: "[Hush, hush, somebody’s callin’ my name]",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(129),
            title: "I am thine, O Lord, I have heard thy voice",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(130),
            title: "Glory, glory, hallelujah! ",
            tune: "[Glory, glory, hallelujah!]",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(131),
            title: "Did ever you see the like before",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(132),
            title: "Have you got good religion?",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(133),
            title: "All to Jesus I surrender",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(134),
            title: "Take me to the water",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(135),
            title: "You have longed for sweet peace",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(136),
            title: "I have decided to follow Jesus",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(137),
            title: "Just as I am, without one plea",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(138),
            title: "Lord, I want to be a Christian",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(139),
            title: "Pass me not, O gentle Savior",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(140),
            title: "Some folks want treasures of silver and gold",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(141),
            title: "Shall we gather at the river",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(142),
            title: "Sign me up for the Christian jubilee",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(143),
            title: "See that host all dressed in white",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(144),
            title: "I can hear my Savior calling",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(145),
            title: "Have thine own way, Lord!",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(146),
            title: "Break thou the bread of life",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(147),
            title: "Come, ye disconsolate, where’er ye languish",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(148),
            title: "I’m a-going to eat at the welcome table",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(149),
            title: "In remembrance of me, eat this bread",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(150),
            title: "I am the Bread that came down from heaven",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(151),
            title: "Gentile or Jew, servant or free",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(152),
            title: "Let us break bread together on our knees",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(153),
            title: "Lord I have seen thy salvation",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(154),
            title: "I will bless the Lord at all times",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(155),
            title: "This is my body given up for you",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(156),
            title: "Come to me, Ye who are hard oppressed",
            tune: "[“Come to me, Ye who are hard oppressed]",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(157),
            title: "We praise thee, O God",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(158),
            title: "Out in the highways and byways of life",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(159),
            title: "How to reach the masses, those of ev’ry birth",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(160),
            title: "This little light of mine",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(161),
            title: "“Go preach my gospel,” saith the Lord",
            tune: "[“Go preach my gospel,” saith the Lord]",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(162),
            title: "Come by here Lord",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(163),
            title: "No harm have I done you on my knees",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(164),
            title: "Do Lord, do Lord",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(165),
            title: "I’m pressing on the upward way",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(166),
            title: "Lord, my soul is thirsting for a blessing today",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(167),
            title: "Lord I hear of show’rs of blessings",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(168),
            title: "I have a Savior, He’s pleading in glory",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(169),
            title: "Sometimes I feel like a motherless chile",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(170),
            title: "Yield not to temptation",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(171),
            title: "In de valley",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(172),
            title: "Brother will you pray for me?",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(173),
            title: "Lord, I want to live for thee",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(174),
            title: "Let the heav’n light shine on me",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(175),
            title: "Sometimes I’m up, sometimes I’m down",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(176),
            title: "If I have wounded any soul today",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(177),
            title: "Not my brother, not my sister, but it’s me, O Lord",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(178),
            title: "Sweet hour of prayer, sweet hour of prayer",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(179),
            title: "Remember me, Remember me",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(180),
            title: "I got a robe up in-a that kingdom",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(181),
            title: "Amazing grace! how sweet the sound",
            tune: "NEW BRITAIN",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(182),
            title: "He delivered Daniel from the lion’s den",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(183),
            title: "Be not dismayed whate’er betide",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(184),
            title: "Blessed assurance, Jesus is mine!",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(185),
            title: "Joys are flowing like a river",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(186),
            title: "I can do all things through Christ who strengthens me",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(187),
            title: "Tempted and tried we’re oft made to wonder",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(188),
            title: "When peace, like a river, attendeth my way",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(189),
            title: "Great is thy faithfulness, O God my Father",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(190),
            title: "If when you give the best of your service",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(191),
            title: "Why should I feel discouraged",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(192),
            title: "I need thee ev’ry hour",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(193),
            title: "I will trust in the Lord",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(194),
            title: "I am weak and I need thy strength and power",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(195),
            title: "I’ve been ’buked an’ I’ve been scorned",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(196),
            title: "What a fellowship, what a joy divine",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(197),
            title: "If the world from you withhold",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(198),
            title: "I was sinking deep in sin",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(199),
            title: "I don’t feel no ways tired",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(200),
            title: "When the storms of life are raging",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(201),
            title: "I’ve got peace like a river",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(202),
            title: "The church of God must now prevail",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(203),
            title: "Sometimes I feel discouraged",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(204),
            title: "When waves of affliction sweep over the soul",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(205),
            title: "When we walk with the Lord",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(206),
            title: "We walk by faith, and not by sight",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(207),
            title: "We are often tossed and driv’n",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(208),
            title: "Don’t be discouraged when trouble’s in your life",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(209),
            title: "There are some things I may not know",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(210),
            title: "Goin’ to lay down my sword and shield",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(211),
            title: "Little David was a shepherd boy",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(212),
            title: "Born to rule the earth",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(213),
            title: "Children of the heav’nly Father",
            tune: "[Children of the heav’nly Father]",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(214),
            title: "God is so good",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(215),
            title: "God, our Father, we adore you, magnify you",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(216),
            title: "In my life, Lord, be glorified, be glorified",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(217),
            title: "He’s got the whole world in His hand",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(218),
            title: "Jesus loves me! this I know",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(219),
            title: "This is the day, this the day",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(220),
            title: "We are climbing Jacob’s ladder",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(221),
            title: "This little light of mine, I’m gonna let it shine",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(222),
            title: "Jesus loves the little children",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(223),
            title: "You may talk about the man of Gideon",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(224),
            title: "Better min’, my sister",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(225),
            title: "Oh, freedom! Oh, freedom",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(226),
            title: "Mine eyes have seen the glory",
            tune: "BATTLE HYMN OF THE REPUBLIC",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(227),
            title: "We shall overcome",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(228),
            title: "When Israel was in Egypt’s land",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(229),
            title: "Martin’s dream for all of us so set his soul afire",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(230),
            title: "’Way down yonder in the graveyard walk",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(231),
            title: "The Lord bless you and keep you",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(232),
            title: "Thank you, Lord",
            tune: "[Thank you, Lord, Thank you, Lord]",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(233),
            title: "See the little baby",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(234),
            title: "God be with you, God be with you",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(235),
            title: "Lord have mercy, Lord have mercy",
            tune: "[Lord have mercy, Lord have mercy, Lord have mercy]",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(236),
            title: "Lord, have mercy",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(237),
            title: "Lord, have mercy",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(238),
            title: "Lord, have mercy",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(239),
            title: "Kyrie eleison",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(240),
            title: "Lord, have mercy",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(241),
            title: "Glory to God in the highest",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(242),
            title: "Glory to God in the highest",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(243),
            title: "Glory, Glory, hallelujah",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(244),
            title: "I will praise the Father",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(245),
            title: "We have come into His house",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(246),
            title: "Praise, praise, honor and glory",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(247),
            title: "With all our heart and with all our mind",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(248),
            title: "Let us pray for the Church and for the world",
            tune: "[Let us pray for the Church and for the world] (Pulkingham)",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(249),
            title: "Hear our prayer, O Lord",
            tune: "[Hear our prayer, O Lord, hear our prayer, O Lord]",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(250),
            title: "O Lord, Hear us, we pray",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(251),
            title: "Lead me, Lord, lead me in thy righteousness",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(252),
            title: "Holy, holy, holy Lord, God of power and might",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(253),
            title: "Holy, holy, holy Lord, God of power and might",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(254),
            title: "Holy, holy, holy Lord, God of power and might",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(255),
            title: "Holy, holy, holy, holy, holy Lord God of hosts",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(256),
            title: "Holy, holy, holy Lord, God of pow’r and might",
            tune: "[Holy, holy, holy Lord, God of pow’r and might]",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(257),
            title: "Therefore we proclaim the mystery of faith",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(258),
            title: "Christ has died",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(259),
            title: "Christ has died",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(260),
            title: "We remember His death",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(261),
            title: "Amen",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(262),
            title: "Amen",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(263),
            title: "Our Father in heaven",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(264),
            title: "Our Father, which art in heaven",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(265),
            title: "Our Father in heaven",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(266),
            title: "Our Father in heaven",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(267),
            title: "Our Father, who art in heaven",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(268),
            title: "Christ our passover is sacrificed for us",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(269),
            title: "Lamb of God, you take away the sins of the world",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(270),
            title: "Lamb of God, you take away the sins of the world",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(271),
            title: "Lamb of God, you take away the sins of the world",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(272),
            title: "Do this in remembrance of me",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(273),
            title: "His love, His love, His love is everlasting",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(274),
            title: "The Lord is gracious and full of compassion",
            tune: "[I will praise your name forever]",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(275),
            title: "Lord, send out your spirit!",
            tune: "[Lord, send out your spirit]",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(276),
            title: "My God, My God, why have you abandoned me?",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(277),
            title: "The Lord is my light and my salvation",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(278),
            title: "Serve the Lord with gladness, alleluia",
            tune: "",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(279),
            title: "The Lord is my shepherd; there is nothing I shall want",
            tune: "[The Lord is my shepherd]",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(280),
            title: "To you, O Lord, I lift up my soul",
            tune: "[To you, O Lord, I lift up my soul",
        },
        Hymn {
            source: Hymnals::LEVAS,
            number: HymnNumber::H(281),
            title: "Bless, O Lord, our country, Africa ",
            tune: "[Bless, O Lord, our country, Africa]",
        },
    ],
};
