[package]
name = "document_page"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
website = { path = "../../website" }
leptos = { path = "../../../framework/leptos" }
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }