[package]
name = "library"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"]}
lazy_static = '1.0'
api = { path = "../api" }
language = { path = "../language" }
lectionary = { path = "../lectionary" }
liturgy = { path = "../liturgy" }
calendar = { path = "../calendar" }
canticle-table = {path = "../canticle-table" }
psalter = { path = "../psalter" }
reference-parser = { path = "../reference-parser" }
