[package]
name = "canticle-table"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"]}
strum = "0.24"
strum_macros = "0.24"
lazy_static = "1"
calendar = { path = "../calendar" }