[workspace]
members = [
  "client/calendar",
  "client/canticle_table",
  "client/daily_office",
  "client/daily_readings",
  "client/document",
  "client/holy_day",
  "client/hymnal",
  "client/index",
  "client/settings",
  "server",
  "website"
]