use language::Language;

use crate::{
    feasts::KalendarEntry, holy_day::HolyDayId, liturgical_week::Cycle, Calendar, Feast,
    LiturgicalWeek, Proper, Rank, Season, Time, Weekday,
};

/// [Calendar](Calendar) that calculates dates from the liturgical and sanctoral calendar
/// of the 1979 Book of Common Prayer of The Episcopal Church.
pub const BCP1979_CALENDAR: Calendar = Calendar {
    easter_cycle_begins: 7,
    christmas_cycle_begins: 4,
    has_propers: true,
    weeks: &BCP1979_WEEKS,
    holy_days: &BCP1979_FEASTS,
    holy_day_ranks: &BCP1979_HOLY_DAY_RANKS,
    feast_seasons: &BCP1979_HOLY_DAY_SEASONS,
    week_seasons: &BCP1979_WEEK_SEASONS,
    feast_names: &BCP1979_FEAST_NAMES,
    week_names: &BCP1979_WEEK_NAMES,
    proper_names: &BCP1979_PROPER_NAMES,
};

pub(crate) const BCP1979_WEEKS: [(Cycle, u8, LiturgicalWeek); 59] = [
    (Cycle::Advent, 0, LiturgicalWeek::LastPentecost),
    (Cycle::Advent, 1, LiturgicalWeek::Advent1),
    (Cycle::Advent, 2, LiturgicalWeek::Advent2),
    (Cycle::Advent, 3, LiturgicalWeek::Advent3),
    (Cycle::Advent, 4, LiturgicalWeek::Advent4),
    (Cycle::Christmas, 0, LiturgicalWeek::Christmas),
    (Cycle::Christmas, 1, LiturgicalWeek::Christmas1),
    (Cycle::Christmas, 2, LiturgicalWeek::Christmas2),
    (Cycle::Epiphany, 0, LiturgicalWeek::Epiphany),
    (Cycle::Epiphany, 1, LiturgicalWeek::Epiphany1),
    (Cycle::Epiphany, 2, LiturgicalWeek::Epiphany2),
    (Cycle::Epiphany, 3, LiturgicalWeek::Epiphany3),
    (Cycle::Epiphany, 4, LiturgicalWeek::Epiphany4),
    (Cycle::Epiphany, 5, LiturgicalWeek::Epiphany5),
    (Cycle::Epiphany, 6, LiturgicalWeek::Epiphany6),
    (Cycle::Epiphany, 7, LiturgicalWeek::Epiphany7),
    (Cycle::Epiphany, 8, LiturgicalWeek::Epiphany8),
    (Cycle::Easter, 0, LiturgicalWeek::LastEpiphany),
    (Cycle::Easter, 1, LiturgicalWeek::Lent1),
    (Cycle::Easter, 2, LiturgicalWeek::Lent2),
    (Cycle::Easter, 3, LiturgicalWeek::Lent3),
    (Cycle::Easter, 4, LiturgicalWeek::Lent4),
    (Cycle::Easter, 5, LiturgicalWeek::Lent5),
    (Cycle::Easter, 6, LiturgicalWeek::HolyWeek),
    (Cycle::Easter, 7, LiturgicalWeek::Easter),
    (Cycle::Easter, 8, LiturgicalWeek::Easter2),
    (Cycle::Easter, 9, LiturgicalWeek::Easter3),
    (Cycle::Easter, 10, LiturgicalWeek::Easter4),
    (Cycle::Easter, 11, LiturgicalWeek::Easter5),
    (Cycle::Easter, 12, LiturgicalWeek::Easter6),
    (Cycle::Easter, 13, LiturgicalWeek::Easter7),
    (Cycle::Easter, 14, LiturgicalWeek::Pentecost),
    (Cycle::Easter, 15, LiturgicalWeek::TrinitySunday),
    (Cycle::Easter, 16, LiturgicalWeek::Pentecost2),
    (Cycle::Easter, 17, LiturgicalWeek::Pentecost3),
    (Cycle::Easter, 18, LiturgicalWeek::Pentecost4),
    (Cycle::Easter, 19, LiturgicalWeek::Pentecost5),
    (Cycle::Easter, 20, LiturgicalWeek::Pentecost6),
    (Cycle::Easter, 21, LiturgicalWeek::Pentecost7),
    (Cycle::Easter, 22, LiturgicalWeek::Pentecost8),
    (Cycle::Easter, 23, LiturgicalWeek::Pentecost9),
    (Cycle::Easter, 24, LiturgicalWeek::Pentecost10),
    (Cycle::Easter, 25, LiturgicalWeek::Pentecost11),
    (Cycle::Easter, 26, LiturgicalWeek::Pentecost12),
    (Cycle::Easter, 27, LiturgicalWeek::Pentecost13),
    (Cycle::Easter, 28, LiturgicalWeek::Pentecost14),
    (Cycle::Easter, 29, LiturgicalWeek::Pentecost15),
    (Cycle::Easter, 30, LiturgicalWeek::Pentecost16),
    (Cycle::Easter, 31, LiturgicalWeek::Pentecost17),
    (Cycle::Easter, 32, LiturgicalWeek::Pentecost18),
    (Cycle::Easter, 33, LiturgicalWeek::Pentecost19),
    (Cycle::Easter, 34, LiturgicalWeek::Pentecost20),
    (Cycle::Easter, 35, LiturgicalWeek::Pentecost21),
    (Cycle::Easter, 36, LiturgicalWeek::Pentecost22),
    (Cycle::Easter, 37, LiturgicalWeek::Pentecost23),
    (Cycle::Easter, 38, LiturgicalWeek::Pentecost24),
    (Cycle::Easter, 39, LiturgicalWeek::Pentecost25),
    (Cycle::Easter, 40, LiturgicalWeek::Pentecost26),
    (Cycle::Easter, 41, LiturgicalWeek::Pentecost27),
];

pub(crate) const BCP1979_WEEK_SEASONS: [(LiturgicalWeek, Season); 31] = [
    (LiturgicalWeek::Advent1, Season::Advent),
    (LiturgicalWeek::Advent2, Season::Advent),
    (LiturgicalWeek::Advent3, Season::Advent),
    (LiturgicalWeek::Advent4, Season::Advent),
    (LiturgicalWeek::Christmas, Season::Christmas),
    (LiturgicalWeek::Christmas1, Season::Christmas),
    (LiturgicalWeek::Christmas2, Season::Christmas),
    (LiturgicalWeek::Epiphany, Season::Epiphany),
    (LiturgicalWeek::Epiphany1, Season::Epiphany),
    (LiturgicalWeek::Epiphany2, Season::Epiphany),
    (LiturgicalWeek::Epiphany3, Season::Epiphany),
    (LiturgicalWeek::Epiphany4, Season::Epiphany),
    (LiturgicalWeek::Epiphany5, Season::Epiphany),
    (LiturgicalWeek::Epiphany6, Season::Epiphany),
    (LiturgicalWeek::Epiphany7, Season::Epiphany),
    (LiturgicalWeek::Epiphany8, Season::Epiphany),
    (LiturgicalWeek::LastEpiphany, Season::Epiphany),
    (LiturgicalWeek::Lent1, Season::Lent),
    (LiturgicalWeek::Lent2, Season::Lent),
    (LiturgicalWeek::Lent3, Season::Lent),
    (LiturgicalWeek::Lent4, Season::Lent),
    (LiturgicalWeek::Lent5, Season::Lent),
    (LiturgicalWeek::HolyWeek, Season::HolyWeek),
    (LiturgicalWeek::Easter, Season::Easter),
    (LiturgicalWeek::Easter2, Season::Easter),
    (LiturgicalWeek::Easter3, Season::Easter),
    (LiturgicalWeek::Easter4, Season::Easter),
    (LiturgicalWeek::Easter5, Season::Easter),
    (LiturgicalWeek::Easter6, Season::Easter),
    (LiturgicalWeek::Easter7, Season::Ascension),
    (LiturgicalWeek::Pentecost, Season::Pentecost),
    // Algorithm defaults to Season::OrdinaryTime, so can ignore the season after Pentecost
    // This will (nominally, but not relevantly) reduce search times since this is O(n)
];

pub(crate) const BCP1979_HOLY_DAY_SEASONS: [(Feast, Season); 35] = [
    (Feast::ChristmasDay, Season::Christmas),
    (Feast::December29, Season::Christmas),
    (Feast::December30, Season::Christmas),
    (Feast::Epiphany, Season::Epiphany),
    (Feast::EveOfHolyCross, Season::HolyWeek),
    (Feast::FridayAfterAscension, Season::Ascension),
    (Feast::FridayInEasterWeek, Season::Easter),
    (Feast::GoodFriday, Season::HolyWeek),
    (Feast::FridayAfterAshWednesday, Season::Lent),
    (Feast::HolyCross, Season::HolyWeek),
    (Feast::HolyName, Season::Christmas),
    (Feast::January2, Season::Christmas),
    (Feast::January3, Season::Christmas),
    (Feast::January4, Season::Christmas),
    (Feast::MondayInEasterWeek, Season::Easter),
    (Feast::MondayInHolyWeek, Season::HolyWeek),
    (Feast::SaturdayAfterAscension, Season::Ascension),
    (Feast::EveOfPentecost, Season::Pentecost),
    (Feast::SaturdayInEasterWeek, Season::Easter),
    (Feast::HolySaturday, Season::HolyWeek),
    (Feast::SaturdayAfterAshWednesday, Season::Lent),
    (Feast::PalmSunday, Season::HolyWeek),
    (Feast::Pentecost, Season::Pentecost),
    (Feast::EveOfTrinitySunday, Season::Trinity),
    (Feast::TrinitySunday, Season::Trinity),
    (Feast::AscensionDay, Season::Ascension),
    (Feast::ThursdayInEasterWeek, Season::Easter),
    (Feast::MaundyThursday, Season::HolyWeek),
    (Feast::ThursdayAfterAshWednesday, Season::Lent),
    (Feast::TuesdayInEasterWeek, Season::Easter),
    (Feast::TuesdayInHolyWeek, Season::HolyWeek),
    (Feast::EveOfTheAscension, Season::Ascension),
    (Feast::WednesdayInEasterWeek, Season::Easter),
    (Feast::WednesdayInHolyWeek, Season::HolyWeek),
    (Feast::AshWednesday, Season::Lent),
];

pub(crate) const BCP1979_HOLY_DAY_RANKS: [(Feast, Rank); 86] = [
    (Feast::EveOfAllSaints, Rank::PrincipalFeast),
    (Feast::AllSaintsDay, Rank::PrincipalFeast),
    (Feast::ChristmasDay, Rank::PrincipalFeast),
    (Feast::ChristmasEve, Rank::PrincipalFeast),
    (Feast::EveOfEpiphany, Rank::PrincipalFeast),
    (Feast::Epiphany, Rank::PrincipalFeast),
    (Feast::EveOfHolyName, Rank::PrincipalFeast),
    (Feast::HolyName, Rank::PrincipalFeast),
    (Feast::EveOfPentecost, Rank::PrincipalFeast),
    (Feast::PalmSunday, Rank::PrincipalFeast),
    (Feast::EasterSunday, Rank::PrincipalFeast),
    (Feast::Pentecost, Rank::PrincipalFeast),
    (Feast::TrinitySunday, Rank::PrincipalFeast),
    (Feast::AscensionDay, Rank::PrincipalFeast),
    (Feast::EveOfTheAscension, Rank::PrincipalFeast),
    (Feast::EveOfEpiphany1, Rank::Sunday),
    (Feast::FridayInEasterWeek, Rank::PrecedenceOverHolyDay),
    (Feast::GoodFriday, Rank::PrecedenceOverHolyDay),
    (Feast::MondayInEasterWeek, Rank::PrecedenceOverHolyDay),
    (Feast::MondayInHolyWeek, Rank::PrecedenceOverHolyDay),
    (Feast::SaturdayInEasterWeek, Rank::PrecedenceOverHolyDay),
    (Feast::HolySaturday, Rank::PrecedenceOverHolyDay),
    (Feast::ThursdayInEasterWeek, Rank::PrecedenceOverHolyDay),
    (Feast::MaundyThursday, Rank::PrecedenceOverHolyDay),
    (Feast::TuesdayInEasterWeek, Rank::PrecedenceOverHolyDay),
    (Feast::TuesdayInHolyWeek, Rank::PrecedenceOverHolyDay),
    (Feast::WednesdayInEasterWeek, Rank::PrecedenceOverHolyDay),
    (Feast::WednesdayInHolyWeek, Rank::PrecedenceOverHolyDay),
    (Feast::AllSoulsDay, Rank::OptionalObservance),
    (Feast::Annunciation, Rank::HolyDay),
    (Feast::ConfessionOfStPeter, Rank::HolyDay),
    (Feast::ConversionOfStPaul, Rank::HolyDay),
    (Feast::EveOfHolyCross, Rank::HolyDay),
    (Feast::EveOfStJohnTheBaptist, Rank::HolyDay),
    (Feast::EveOfTheAnnunciation, Rank::HolyDay),
    (Feast::EveOfThePresentation, Rank::HolyDay),
    (Feast::EveOfTheTransfiguration, Rank::HolyDay),
    (Feast::EveOfTheVisitation, Rank::HolyDay),
    (Feast::FridayAfterAscension, Rank::PrecedenceOverWeekday),
    (Feast::FridayAfterAshWednesday, Rank::PrecedenceOverWeekday),
    (Feast::HolyCross, Rank::HolyDay),
    (Feast::HolyInnocents, Rank::HolyDay),
    (Feast::IndependenceDay, Rank::HolyDay),
    (Feast::NativityOfStJohnTheBaptist, Rank::HolyDay),
    (Feast::SaturdayAfterAscension, Rank::PrecedenceOverWeekday),
    (
        Feast::SaturdayAfterAshWednesday,
        Rank::PrecedenceOverWeekday,
    ),
    (Feast::PeterAndPaul, Rank::HolyDay),
    (Feast::PhilipAndJames, Rank::HolyDay),
    (Feast::SimonAndJude, Rank::HolyDay),
    (Feast::Andrew, Rank::HolyDay),
    (Feast::Barnabas, Rank::HolyDay),
    (Feast::Bartholomew, Rank::HolyDay),
    (Feast::James, Rank::HolyDay),
    (Feast::JamesOfJerusalem, Rank::HolyDay),
    (Feast::John, Rank::HolyDay),
    (Feast::Joseph, Rank::HolyDay),
    (Feast::Luke, Rank::HolyDay),
    (Feast::Mark, Rank::HolyDay),
    (Feast::MaryMagdalene, Rank::HolyDay),
    (Feast::Mary, Rank::HolyDay),
    (Feast::Matthew, Rank::HolyDay),
    (Feast::Matthias, Rank::HolyDay),
    (Feast::Michael, Rank::HolyDay),
    (Feast::Stephen, Rank::HolyDay),
    (Feast::Thomas, Rank::HolyDay),
    (Feast::EveOfTrinitySunday, Rank::HolyDay),
    (Feast::ThanksgivingDay, Rank::HolyDay),
    (Feast::ThePresentation, Rank::HolyDay),
    (Feast::TheTransfiguration, Rank::HolyDay),
    (Feast::TheVisitation, Rank::HolyDay),
    (
        Feast::ThursdayAfterAshWednesday,
        Rank::PrecedenceOverWeekday,
    ),
    (Feast::AshWednesday, Rank::HolyDay),
    (Feast::December24, Rank::PrecedenceOverWeekday),
    (Feast::December29, Rank::PrecedenceOverWeekday),
    (Feast::December30, Rank::PrecedenceOverWeekday),
    (Feast::December31, Rank::PrecedenceOverWeekday),
    (Feast::January2, Rank::PrecedenceOverWeekday),
    (Feast::January3, Rank::PrecedenceOverWeekday),
    (Feast::January4, Rank::PrecedenceOverWeekday),
    (Feast::January5, Rank::PrecedenceOverWeekday),
    (Feast::January7, Rank::PrecedenceOverWeekday),
    (Feast::January8, Rank::PrecedenceOverWeekday),
    (Feast::January9, Rank::PrecedenceOverWeekday),
    (Feast::January10, Rank::PrecedenceOverWeekday),
    (Feast::January11, Rank::PrecedenceOverWeekday),
    (Feast::January12, Rank::PrecedenceOverWeekday),
];

/// Array of all observances in the BCP 1979 calendar
pub const BCP1979_FEASTS: [KalendarEntry; 200] = [
    // Thanksgiving, Labor Day, All Saints’ Sunday
    (
        HolyDayId::DayOfMonth {
            month: 9,
            week: 1,
            day: Weekday::Mon,
        },
        Feast::LaborDay,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::DayOfMonth {
            month: 11,
            week: 4,
            day: Weekday::Thu,
        },
        Feast::ThanksgivingDay,
        Time::AllDay,
        None,
    ),
    // Special days
    (
        HolyDayId::SpecialDay(LiturgicalWeek::Epiphany, Weekday::Sat),
        Feast::EveOfEpiphany1,
        Time::EveningOnly,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::LastEpiphany, Weekday::Wed),
        Feast::AshWednesday,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::LastEpiphany, Weekday::Thu),
        Feast::ThursdayAfterAshWednesday,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::LastEpiphany, Weekday::Fri),
        Feast::FridayAfterAshWednesday,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::LastEpiphany, Weekday::Sat),
        Feast::SaturdayAfterAshWednesday,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::HolyWeek, Weekday::Sun),
        Feast::PalmSunday,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::HolyWeek, Weekday::Mon),
        Feast::MondayInHolyWeek,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::HolyWeek, Weekday::Tue),
        Feast::TuesdayInHolyWeek,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::HolyWeek, Weekday::Wed),
        Feast::WednesdayInHolyWeek,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::HolyWeek, Weekday::Thu),
        Feast::MaundyThursday,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::HolyWeek, Weekday::Fri),
        Feast::GoodFriday,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::HolyWeek, Weekday::Sat),
        Feast::HolySaturday,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::Easter, Weekday::Sun),
        Feast::EasterSunday,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::Easter, Weekday::Mon),
        Feast::MondayInEasterWeek,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::Easter, Weekday::Tue),
        Feast::TuesdayInEasterWeek,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::Easter, Weekday::Wed),
        Feast::WednesdayInEasterWeek,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::Easter, Weekday::Thu),
        Feast::ThursdayInEasterWeek,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::Easter, Weekday::Fri),
        Feast::FridayInEasterWeek,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::Easter, Weekday::Sat),
        Feast::SaturdayInEasterWeek,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::Easter6, Weekday::Wed),
        Feast::EveOfTheAscension,
        Time::EveningOnly,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::Easter6, Weekday::Thu),
        Feast::AscensionDay,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::Easter6, Weekday::Fri),
        Feast::FridayAfterAscension,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::Easter6, Weekday::Sat),
        Feast::SaturdayAfterAscension,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::Easter7, Weekday::Sat),
        Feast::EveOfPentecost,
        Time::EveningOnly,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::Pentecost, Weekday::Sun),
        Feast::Pentecost,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::Pentecost, Weekday::Sat),
        Feast::EveOfTrinitySunday,
        Time::EveningOnly,
        None,
    ),
    (
        HolyDayId::SpecialDay(LiturgicalWeek::TrinitySunday, Weekday::Sun),
        Feast::TrinitySunday,
        Time::AllDay,
        None,
    ),
    // MM/DD feast days
    (HolyDayId::Date(1, 1), Feast::HolyName, Time::AllDay, None),
    (HolyDayId::Date(1, 2), Feast::January2, Time::AllDay, None),
    (HolyDayId::Date(1, 3), Feast::January3, Time::AllDay, None),
    (HolyDayId::Date(1, 4), Feast::January4, Time::AllDay, None),
    (
        HolyDayId::Date(1, 5),
        Feast::January5,
        Time::MorningOnly,
        None,
    ),
    (
        HolyDayId::Date(1, 5),
        Feast::EveOfEpiphany,
        Time::EveningOnly,
        None,
    ),
    (HolyDayId::Date(1, 6), Feast::Epiphany, Time::AllDay, None),
    (
        HolyDayId::Date(1, 7),
        Feast::January7,
        Time::AllDay,
        Some(LiturgicalWeek::Epiphany1),
    ),
    (
        HolyDayId::Date(1, 8),
        Feast::January8,
        Time::AllDay,
        Some(LiturgicalWeek::Epiphany1),
    ),
    (
        HolyDayId::Date(1, 9),
        Feast::January9,
        Time::AllDay,
        Some(LiturgicalWeek::Epiphany1),
    ),
    (
        HolyDayId::Date(1, 10),
        Feast::January10,
        Time::AllDay,
        Some(LiturgicalWeek::Epiphany1),
    ),
    (
        HolyDayId::Date(1, 10),
        Feast::WilliamLaud,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(1, 11),
        Feast::January11,
        Time::AllDay,
        Some(LiturgicalWeek::Epiphany1),
    ),
    (
        HolyDayId::Date(1, 12),
        Feast::January12,
        Time::AllDay,
        Some(LiturgicalWeek::Epiphany1),
    ),
    (
        HolyDayId::Date(1, 13),
        Feast::HilaryOfPoitiers,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(1, 17),
        Feast::AntonyOfEgypt,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(1, 18),
        Feast::ConfessionOfStPeter,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(1, 20), Feast::Fabian, Time::AllDay, None),
    (
        HolyDayId::Date(1, 21),
        Feast::AgnesAndCeciliaOfRome,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(1, 22),
        Feast::VincentOfSaragossa,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(1, 23),
        Feast::PhillipsBrooks,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(1, 25),
        Feast::ConversionOfStPaul,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(1, 26),
        Feast::TitusAndTimothy,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(1, 27),
        Feast::JohnChrysostom,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(1, 28),
        Feast::ThomasAquinas,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(2, 1),
        Feast::EveOfThePresentation,
        Time::EveningOnly,
        None,
    ),
    (
        HolyDayId::Date(2, 2),
        Feast::ThePresentation,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(2, 3), Feast::Anskar, Time::AllDay, None),
    (
        HolyDayId::Date(2, 5),
        Feast::TheMartyrsOfJapan,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(2, 13),
        Feast::AbsalomJones,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(2, 14),
        Feast::CyrilAndMethodius,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(2, 15),
        Feast::ThomasBray,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(2, 23),
        Feast::PolycarpOfSmyrna,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(2, 24), Feast::Matthias, Time::AllDay, None),
    (
        HolyDayId::Date(2, 27),
        Feast::GeorgeHerbert,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(3, 1),
        Feast::DavidOfWales,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(3, 2),
        Feast::ChadOfLichfield,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(3, 3),
        Feast::JohnAndCharlesWesley,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(3, 7),
        Feast::PerpetuaAndFelicity,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(3, 12),
        Feast::GregoryTheGreat,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(3, 17),
        Feast::PatrickOfIreland,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(3, 18),
        Feast::CyrilOfJerusalem,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(3, 19), Feast::Joseph, Time::AllDay, None),
    (HolyDayId::Date(3, 20), Feast::Cuthbert, Time::AllDay, None),
    (HolyDayId::Date(3, 21), Feast::ThomasKen, Time::AllDay, None),
    (
        HolyDayId::Date(3, 22),
        Feast::JamesDeKoven,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(3, 23),
        Feast::GregoryTheIlluminator,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(3, 24),
        Feast::EveOfTheAnnunciation,
        Time::EveningOnly,
        None,
    ),
    (
        HolyDayId::Date(3, 25),
        Feast::Annunciation,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(3, 27),
        Feast::CharlesHenryBrent,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(3, 29), Feast::JohnKeble, Time::AllDay, None),
    (HolyDayId::Date(3, 31), Feast::JohnDonne, Time::AllDay, None),
    (
        HolyDayId::Date(4, 1),
        Feast::FrederickDenisonMaurice,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(4, 2),
        Feast::JamesLloydBreck,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(4, 3),
        Feast::RichardOfChichester,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(4, 8),
        Feast::WilliamAugustusMuhlenberg,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(4, 9), Feast::WilliamLaw, Time::AllDay, None),
    (
        HolyDayId::Date(4, 11),
        Feast::GeorgeAugustusSelwyn,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(4, 19), Feast::Alphege, Time::AllDay, None),
    (
        HolyDayId::Date(4, 21),
        Feast::AnselmOfCanterbury,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(4, 25), Feast::Mark, Time::AllDay, None),
    (
        HolyDayId::Date(4, 29),
        Feast::CatherineOfSiena,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(5, 1),
        Feast::PhilipAndJames,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(5, 2),
        Feast::AthanasiusOfAlexandria,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(5, 4), Feast::Monica, Time::AllDay, None),
    (
        HolyDayId::Date(5, 8),
        Feast::JulianOfNorwich,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(5, 9),
        Feast::GregoryOfNazianzus,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(5, 19), Feast::Dunstan, Time::AllDay, None),
    (
        HolyDayId::Date(5, 20),
        Feast::AlcuinOfYork,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(5, 24),
        Feast::JacksonKemper,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(5, 25), Feast::Bede, Time::AllDay, None),
    (
        HolyDayId::Date(5, 26),
        Feast::AugustineOfCanterbury,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(5, 30),
        Feast::EveOfTheVisitation,
        Time::EveningOnly,
        None,
    ),
    (
        HolyDayId::Date(5, 31),
        Feast::TheVisitation,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(6, 1), Feast::Justin, Time::AllDay, None),
    (
        HolyDayId::Date(6, 3),
        Feast::TheMartyrsOfUganda,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(6, 5), Feast::Boniface, Time::AllDay, None),
    (
        HolyDayId::Date(6, 9),
        Feast::ColumbaOfIona,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(6, 10),
        Feast::EphremOfNisibis,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(6, 11), Feast::Barnabas, Time::AllDay, None),
    (
        HolyDayId::Date(6, 14),
        Feast::BasilOfCaesarea,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(6, 16),
        Feast::JosephButler,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(6, 18),
        Feast::BernardMizeki,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(1, 19),
        Feast::WulfstanOfWorcester,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(6, 22), Feast::Alban, Time::AllDay, None),
    (
        HolyDayId::Date(6, 23),
        Feast::EveOfStJohnTheBaptist,
        Time::EveningOnly,
        None,
    ),
    (
        HolyDayId::Date(6, 24),
        Feast::NativityOfStJohnTheBaptist,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(6, 28),
        Feast::IrenaeusOfLyons,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(6, 29),
        Feast::PeterAndPaul,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(7, 4),
        Feast::IndependenceDay,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(7, 11),
        Feast::BenedictOfNursia,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(7, 17),
        Feast::WilliamWhite,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(7, 22),
        Feast::MaryMagdalene,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(7, 24),
        Feast::ThomasAKempis,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(7, 25), Feast::James, Time::AllDay, None),
    (
        HolyDayId::Date(7, 27),
        Feast::WilliamReedHuntington,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(7, 30),
        Feast::WilliamWilberforce,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(7, 31),
        Feast::JosephOfArimathea,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(8, 5),
        Feast::EveOfTheTransfiguration,
        Time::EveningOnly,
        None,
    ),
    (
        HolyDayId::Date(8, 6),
        Feast::TheTransfiguration,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(8, 7),
        Feast::JohnMasonNeale,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(8, 8), Feast::Dominic, Time::AllDay, None),
    (
        HolyDayId::Date(8, 10),
        Feast::LaurenceOfRome,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(8, 11),
        Feast::ClareOfAssisi,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(8, 13),
        Feast::JeremyTaylor,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(8, 15), Feast::Mary, Time::AllDay, None),
    (
        HolyDayId::Date(8, 18),
        Feast::WilliamPorcherDubose,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(8, 20),
        Feast::BernardOfClairvaux,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(8, 24),
        Feast::Bartholomew,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(8, 25), Feast::Louis, Time::AllDay, None),
    (
        HolyDayId::Date(8, 28),
        Feast::AugustineOfHippo,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(8, 31),
        Feast::AidanOfLindisfarne,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(9, 2),
        Feast::TheMartyrsOfNewGuinea,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(9, 12),
        Feast::JohnHenryHobart,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(9, 13),
        Feast::CyprianOfCarthage,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(9, 13),
        Feast::EveOfHolyCross,
        Time::EveningOnly,
        None,
    ),
    (HolyDayId::Date(9, 14), Feast::HolyCross, Time::AllDay, None),
    (HolyDayId::Date(9, 16), Feast::Ninian, Time::AllDay, None),
    (
        HolyDayId::Date(9, 18),
        Feast::EdwardBouveriePusey,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(9, 19),
        Feast::TheodoreOfTarsus,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(9, 20),
        Feast::JohnColeridgePatteson,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(9, 21), Feast::Matthew, Time::AllDay, None),
    (
        HolyDayId::Date(9, 25),
        Feast::SergiusOfRadonezh,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(9, 26),
        Feast::LancelotAndrewes,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(9, 29), Feast::Michael, Time::AllDay, None),
    (HolyDayId::Date(9, 30), Feast::Jerome, Time::AllDay, None),
    (
        HolyDayId::Date(10, 1),
        Feast::RemigiusOfRheims,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(10, 4),
        Feast::FrancisOfAssisi,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(10, 6),
        Feast::WilliamTyndale,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(10, 9),
        Feast::RobertGrosseteste,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(10, 15),
        Feast::SamuelIsaacJosephScherechewsky,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(10, 16),
        Feast::HughLatimerAndNicholasRidley,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(10, 17),
        Feast::IgnatiusOfAntioch,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(10, 18), Feast::Luke, Time::AllDay, None),
    (
        HolyDayId::Date(10, 19),
        Feast::HenryMartyn,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(10, 23),
        Feast::JamesOfJerusalem,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(10, 26), Feast::Alfred, Time::AllDay, None),
    (
        HolyDayId::Date(10, 28),
        Feast::SimonAndJude,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(10, 29),
        Feast::JamesHannington,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(10, 31),
        Feast::EveOfAllSaints,
        Time::EveningOnly,
        None,
    ),
    (
        HolyDayId::Date(11, 1),
        Feast::AllSaintsDay,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(11, 2),
        Feast::AllSoulsDay,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(11, 3),
        Feast::RichardHooker,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(11, 7),
        Feast::Willibrord,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(11, 10),
        Feast::LeoOfRome,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(11, 11),
        Feast::MartinOfTours,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(11, 12),
        Feast::CharlesSimeon,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(11, 14),
        Feast::SamuelSeabury,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(11, 16),
        Feast::MargaretOfScotland,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(11, 17),
        Feast::HughOfLincoln,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(11, 18),
        Feast::HildaOfWhitby,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(11, 19),
        Feast::ElizabethOfHungary,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(11, 23),
        Feast::ClementOfRome,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(11, 30), Feast::Andrew, Time::AllDay, None),
    (
        HolyDayId::Date(12, 1),
        Feast::NicholasFerrar,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(12, 2),
        Feast::ChanningMooreWilliams,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(12, 4),
        Feast::JohnOfDamascus,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(12, 5),
        Feast::ClementOfAlexandria,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(12, 6),
        Feast::NicholasOfMyra,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(12, 7),
        Feast::AmbroseOfMilan,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(12, 21), Feast::Thomas, Time::AllDay, None),
    (
        HolyDayId::Date(12, 24),
        Feast::December24,
        Time::MorningOnly,
        None,
    ),
    (
        HolyDayId::Date(12, 24),
        Feast::ChristmasEve,
        Time::EveningOnly,
        None,
    ),
    (
        HolyDayId::Date(12, 25),
        Feast::ChristmasDay,
        Time::AllDay,
        None,
    ),
    (HolyDayId::Date(12, 26), Feast::Stephen, Time::AllDay, None),
    (HolyDayId::Date(12, 27), Feast::John, Time::AllDay, None),
    (
        HolyDayId::Date(12, 28),
        Feast::HolyInnocents,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(12, 29),
        Feast::December29,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(12, 30),
        Feast::December30,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(12, 31),
        Feast::December31,
        Time::AllDay,
        None,
    ),
    (
        HolyDayId::Date(12, 31),
        Feast::EveOfHolyName,
        Time::EveningOnly,
        None,
    ),
];

pub(crate) const BCP1979_FEAST_NAMES : [(Feast, Language, &str); 191] = [
    (Feast::AbsalomJones, Language::En, "Absalom Jones, Priest, 1818"),
    (Feast::AgnesAndCeciliaOfRome, Language::En, "Agnes, Martyr at Rome, 304"),
    (Feast::AidanOfLindisfarne, Language::En, "Aidan, Bishop of Lindisfarne, 651"),
    (Feast::Alban, Language::En, "Alban, First Martyr of Britain, c. 304"),
    (Feast::AlcuinOfYork, Language::En, "Alcuin, Deacon, and Abbot of Tours, 804"),
    (Feast::Alfred, Language::En, "Alfred the Great, King of the West Saxons, 889"),
    (Feast::AllSaintsDay, Language::En, "All Saints’ Day"),
    (Feast::AllSoulsDay, Language::En, "Commemoration of All Faithful Departed (All Souls’ Day)"),
    (Feast::Alphege, Language::En, "Alphege, Archbishop of Canterbury, and Martyr, 1012"),
    (Feast::AmbroseOfMilan, Language::En, "Ambrose, Bishop of Milan, 397"),
    (Feast::Annunciation, Language::En, "The Annunciation of Our Lord Jesus Christ to the Blessed Virgin Mary"),
    (Feast::AnselmOfCanterbury, Language::En, "Anselm, Archbishop of Canterbury, 1109"),
    (Feast::Anskar, Language::En, "Anskar, Archbishop of Hamburg, Missionary to Denmark and Sweden, 865"),
    (Feast::AntonyOfEgypt, Language::En, "Antony, Abbot in Egypt, 356"),
    (Feast::AthanasiusOfAlexandria, Language::En, "Athanasius, Bishop of Alexandria, 373"),
    (Feast::AugustineOfHippo, Language::En, "Augustine, Bishop of Hippo, 430"),
    (Feast::AugustineOfCanterbury, Language::En, "Augustine, First Archbishop of Canterbury, 605"),
    (Feast::BasilOfCaesarea, Language::En, "Basil the Great, Bishop of Caesarea, 379"),
    (Feast::Bede, Language::En, "Bede, the Venerable, Priest, and Monk of Jarrow, 735"),
    (Feast::BenedictOfNursia, Language::En, "Benedict of Nursia, Abbot of Monte Cassino, c. 540"),
    (Feast::BernardOfClairvaux, Language::En, "Bernard, Abbot of Clairvaux, 1153"),
    (Feast::BernardMizeki, Language::En, "Bernard, Mizeki, Catechist and Martyr in Rhodesia, 1896"),
    (Feast::Boniface, Language::En, "Boniface, Archbishop of Mainz, Missionary to Germany, and Martyr, 754"),
    (Feast::CatherineOfSiena, Language::En, "Catherine of Siena, 1380"),
    (Feast::ChadOfLichfield, Language::En, "Chad, Bishop of Lichfield, 672"),
    (Feast::ChanningMooreWilliams, Language::En, "Channing Moore Williams, Missionary Bishop in China and Japan, 1910"),
    (Feast::CharlesHenryBrent, Language::En, "Charles Henry Brent, Bishop of the Philippines, and of Western New York, 1929"),
    (Feast::CharlesSimeon, Language::En, "Charles Simeon, Priest, 1836"),
    (Feast::ChristmasDay, Language::En, "Christmas Day"),
    (Feast::ClareOfAssisi, Language::En, "Clare, Abbess at Assisi, 1253"),
    (Feast::ClementOfRome, Language::En, "Clement, Bishop of Rome, c. 100"),
    (Feast::ClementOfAlexandria, Language::En, "Clement of Alexandria, Priest, c. 210"),
    (Feast::ColumbaOfIona, Language::En, "Columba, Abbot of Iona, 597"),
    (Feast::ConfessionOfStPeter, Language::En, "The Confession of St. Peter the Apostle"),
    (Feast::SamuelSeabury, Language::En, "Consecration of Samuel Seabury, First American Bishop, 1784"),
    (Feast::ConversionOfStPaul, Language::En, "The Conversion of St. Paul the Apostle"),
    (Feast::Cuthbert, Language::En, "Cuthbert, Bishop of Lindisfarne, 687"),
    (Feast::CyprianOfCarthage, Language::En, "Cyprian, Bishop and Martyr of Carthage, 258"),
    (Feast::CyrilOfJerusalem, Language::En, "Cyril, Bishop of Jerusalem, 386"),
    (Feast::CyrilAndMethodius, Language::En, "Cyril, Monk, and Methodius, Bishop, Missionaries to the Slavs, 869, 885"),
    (Feast::JulianOfNorwich, Language::En, "Dame Julian of Norwich, c. 1417"),
    (Feast::DavidOfWales, Language::En, "David, Bishop of Menevia, Wales, c. 544"),
    (Feast::Dominic, Language::En, "Dominic, Priest and Friar, 1221"),
    (Feast::Dunstan, Language::En, "Dunstan, Archbishop of Canterbury, 988"),
    (Feast::EdwardBouveriePusey, Language::En, "Edward Bouverie Pusey, Priest, 1882"),
    (Feast::ElizabethOfHungary, Language::En, "Elizabeth, Princess of Hungary, 1231"),
    (Feast::EphremOfNisibis, Language::En, "Ephrem of Edessa, Syria, Deacon, 373"),
    (Feast::Epiphany, Language::En, "The Epiphany"),
    (Feast::EveOfAllSaints, Language::En, "Eve of All Saints’ Day"),
    (Feast::EveOfHolyCross, Language::En, "Eve of Holy Cross Day"),
    (Feast::EveOfStJohnTheBaptist, Language::En, "Eve of the Nativity of St. John the Baptist"),
    (Feast::EveOfTheAnnunciation, Language::En, "Eve of the Annunciation of Our Lord Jesus Christ to the Blessed Virgin Mary"),
    (Feast::EveOfThePresentation, Language::En, "Eve of the Presentation of Our Lord Jesus Christ in the Temple"),
    (Feast::EveOfTheTransfiguration, Language::En, "Eve of the Transfiguration of Our Lord Jesus Christ"),
    (Feast::EveOfTheVisitation, Language::En, "Eve of the Visitation of the Blessed Virgin Mary"),
    (Feast::Fabian, Language::En, "Fabian, Bishop and Martyr of Rome, 250"),
    (Feast::FrancisOfAssisi, Language::En, "Francis of Assisi, Friar, 1226"),
    (Feast::FrederickDenisonMaurice, Language::En, "Frederick Denison Maurice, Priest, 1872"),
    (Feast::FridayAfterAscension, Language::En, "Friday after Ascension Day"),
    (Feast::FridayInEasterWeek, Language::En, "Friday in Easter Week"),
    (Feast::GoodFriday, Language::En, "Good Friday"),
    (Feast::FridayAfterAshWednesday, Language::En, "Friday after Ash Wednesday"),
    (Feast::GeorgeAugustusSelwyn, Language::En, "George Augustus Selwyn, Bishop of New Zealand, and of Litchfield, 1878"),
    (Feast::GeorgeHerbert, Language::En, "George Herbert, Priest, 1633"),
    (Feast::GregoryOfNazianzus, Language::En, "Gregory of Nazianzus, Bishop of Constantinople, 389"),
    (Feast::GregoryTheGreat, Language::En, "Gregory the Great, Bishop of Rome, 604"),
    (Feast::GregoryTheIlluminator, Language::En, "Gregory the Illuminator, Bishop and Missionary of Armenia, c. 332"),
    (Feast::HenryMartyn, Language::En, "Henry Martyn, Priest, and Missionary to India and Persia, 1812"),
    (Feast::HilaryOfPoitiers, Language::En, "Hilary, Bishop of Poitiers, 367"),
    (Feast::HildaOfWhitby, Language::En, "Hilda, Abbess of Whitby, 680"),
    (Feast::HolyCross, Language::En, "Holy Cross Day"),
    (Feast::HolyInnocents, Language::En, "Holy Innocents"),
    (Feast::HolyName, Language::En, "The Holy Name of Our Lord Jesus Christ"),
    (Feast::HughOfLincoln, Language::En, "Hugh, Bishop of Lincoln, 1200"),
    (Feast::HughLatimerAndNicholasRidley, Language::En, "Hugh Latimer and Nicholas Ridley, Bishops, 1555, and Thomas Cranmer, Archbishop of Canterbury, 1556"),
    (Feast::IgnatiusOfAntioch, Language::En, "Ignatius, Bishop of Antioch, and Martyr, c. 115"),
    (Feast::IndependenceDay, Language::En, "Independence Day"),
    (Feast::IrenaeusOfLyons, Language::En, "Irenaeus, Bishop of Lyons, c. 202"),
    (Feast::JacksonKemper, Language::En, "Jackson Kemper, First Missionary Bishop in the United States, 1870"),
    (Feast::JamesDeKoven, Language::En, "James De Koven, Priest, 1879"),
    (Feast::JamesHannington, Language::En, "James Hannington, Bishop of Eastern Equatorial Africa, and his Companions, Martyrs, 1885"),
    (Feast::JamesLloydBreck, Language::En, "James Lloyd Breck, Priest, 1876"),
    (Feast::JeremyTaylor, Language::En, "Jeremy Taylor, Bishop of Down, Connor, and Dromore, 1667"),
    (Feast::Jerome, Language::En, "Jerome, Priest, and Monk of Bethlehem, 420"),
    (Feast::JohnAndCharlesWesley, Language::En, "John and Charles Wesley, Priests, 1791, 1788"),
    (Feast::JohnChrysostom, Language::En, "John Chrysostom, Bishop of Constantinople, 407"),
    (Feast::JohnColeridgePatteson, Language::En, "John Coleridge Patteson, Bishop of Melanesia, and his Companions, Martyrs, 1871"),
    (Feast::JohnDonne, Language::En, "John Donne, Priest, 1631"),
    (Feast::JohnHenryHobart, Language::En, "John Henry Hobart, Bishop of New York, 1830"),
    (Feast::JohnKeble, Language::En, "John Keble, Priest, 1866"),
    (Feast::JohnMasonNeale, Language::En, "John Mason Neale, Priest, 1866"),
    (Feast::JohnOfDamascus, Language::En, "John of Damascus, Priest, c. 760"),
    (Feast::JosephButler, Language::En, "Joseph Butler, Bishop of Durham, 1752"),
    (Feast::JosephOfArimathea, Language::En, "Joseph of Arimathaea"),
    (Feast::Justin, Language::En, "Justin, Martyr at Rome, c. 167"),
    (Feast::LancelotAndrewes, Language::En, "Lancelot Andrewes, Bishop of Winchester"),
    (Feast::LaurenceOfRome, Language::En, "Laurence, Deacon and Martyr at Rome, 258"),
    (Feast::LeoOfRome, Language::En, "Leo the Great, Bishop of Rome, 461"),
    (Feast::Louis, Language::En, "Louis, King of France, 1270"),
    (Feast::MargaretOfScotland, Language::En, "Margaret, Queen of Scotland, 1093"),
    (Feast::MartinOfTours, Language::En, "Martin, Bishop of Tours, 397"),
    (Feast::MondayInEasterWeek, Language::En, "Monday in Easter Week"),
    (Feast::MondayInHolyWeek, Language::En, "Monday in Holy Week"),
    (Feast::Monica, Language::En, "Monnica, Mother of Augustine of Hippo, 387"),
    (Feast::NativityOfStJohnTheBaptist, Language::En, "The Nativity of St. John the Baptist"),
    (Feast::NicholasOfMyra, Language::En, "Nicholas, Bishop of Myra, c. 342"),
    (Feast::NicholasFerrar, Language::En, "Nicholas Ferrar, Deacon, 1637"),
    (Feast::Ninian, Language::En, "Ninian, Bishop in Galloway, c. 430"),
    (Feast::PatrickOfIreland, Language::En, "Patrick, Bishop and Missionary of Ireland, 461"),
    (Feast::PerpetuaAndFelicity, Language::En, "Perpetua and her Companions, Martyrs at Carthage, 202"),
    (Feast::PhillipsBrooks, Language::En, "Phillips Brooks, Bishop of Massachusetts, 1893"),
    (Feast::PolycarpOfSmyrna, Language::En, "Polycarp, Bishop and Martyr of Smyrna, 156"),
    (Feast::RemigiusOfRheims, Language::En, "Remigius, Bishop of Rheims, c. 530"),
    (Feast::RichardOfChichester, Language::En, "Richard, Bishop of Chichester, 1253"),
    (Feast::RichardHooker, Language::En, "Richard Hooker, Priest, 1600"),
    (Feast::RobertGrosseteste, Language::En, "Robert Grosseteste, Bishop of Lincoln, 1253"),
    (Feast::SamuelIsaacJosephScherechewsky, Language::En, "Samuel Isaac Joseph Schereschewsky, Bishop of Shanghai, 1906"),
    (Feast::SaturdayAfterAscension, Language::En, "Saturday after Ascension Day"),
    (Feast::EveOfPentecost, Language::En, "Eve of Pentecost"),
    (Feast::SaturdayInEasterWeek, Language::En, "Saturday in Easter Week"),
    (Feast::HolySaturday, Language::En, "Holy Saturday"),
    (Feast::SaturdayAfterAshWednesday, Language::En, "Saturday after Ash Wednesday"),
    (Feast::SergiusOfRadonezh, Language::En, "Sergius, Abbot of Holy Trinity, Moscow, 1932"),
    (Feast::PeterAndPaul, Language::En, "St. Peter and St. Paul, Apostles"),
    (Feast::PhilipAndJames, Language::En, "St. Philip and St. James, Apostles"),
    (Feast::SimonAndJude, Language::En, "St. Simon and St. Jude, Apostles"),
    (Feast::Andrew, Language::En, "St. Andrew the Apostle"),
    (Feast::Barnabas, Language::En, "St. Barnabas the Apostle"),
    (Feast::Bartholomew, Language::En, "St. Bartholomew the Apostle"),
    (Feast::James, Language::En, "St. James the Apostle"),
    (Feast::JamesOfJerusalem, Language::En, "St. James of Jerusalem, Brother of Our Lord Jesus Christ, and Martyr"),
    (Feast::John, Language::En, "Feast of St. John"),
    (Feast::Joseph, Language::En, "St. Joseph"),
    (Feast::Luke, Language::En, "St. Luke the Evangelist"),
    (Feast::Mark, Language::En, "St. Mark the Evangelist"),
    (Feast::MaryMagdalene, Language::En, "St. Mary Magdalene"),
    (Feast::Mary, Language::En, "St. Mary the Virgin, Mother of Our Lord Jesus Christ"),
    (Feast::Matthew, Language::En, "St. Matthew, Apostle and Evangelist"),
    (Feast::Matthias, Language::En, "St. Matthias the Apostle"),
    (Feast::Michael, Language::En, "St. Michael and All Angels"),
    (Feast::Stephen, Language::En, "Feast of St. Stephen"),
    (Feast::Thomas, Language::En, "St. Thomas the Apostle"),
    (Feast::PalmSunday, Language::En, "Palm Sunday"),
    (Feast::Pentecost, Language::En, "Pentecost"),
    (Feast::EveOfTrinitySunday, Language::En, "Eve of Trinity Sunday"),
    (Feast::TrinitySunday, Language::En, "Trinity Sunday"),
    (Feast::ThanksgivingDay, Language::En, "Thanksgiving Day"),
    (Feast::TheMartyrsOfJapan, Language::En, "The Martyrs of Japan, 1597"),
    (Feast::TheMartyrsOfNewGuinea, Language::En, "The Martyrs of New Guinea, 1942"),
    (Feast::TheMartyrsOfUganda, Language::En, "The Martyrs of Uganda, 1886"),
    (Feast::ThePresentation, Language::En, "The Presentation of Our Lord Jesus Christ in the Temple (Candlemas)"),
    (Feast::TheTransfiguration, Language::En, "The Transfiguration of Our Lord Jesus Christ"),
    (Feast::TheVisitation, Language::En, "The Visitation of the Blessed Virgin Mary"),
    (Feast::TheodoreOfTarsus, Language::En, "Theodore of Tarsus, Archbishop of Canterbury, 690"),
    (Feast::ThomasAKempis, Language::En, "Thomas a Kempis, Priest, 1471"),
    (Feast::ThomasAquinas, Language::En, "Thomas Aquinas, Priest and Friar, 1274"),
    (Feast::ThomasBray, Language::En, "Thomas Bray, Priest and Missionary, 1730"),
    (Feast::ThomasKen, Language::En, "Thomas Ken, Bishop of Bath and Wells, 1711"),
    (Feast::AscensionDay, Language::En, "Ascension Day"),
    (Feast::ThursdayInEasterWeek, Language::En, "Thursday in Easter Week"),
    (Feast::MaundyThursday, Language::En, "Maundy Thursday"),
    (Feast::ThursdayAfterAshWednesday, Language::En, "Thursday after Ash Wednesday"),
    (Feast::TitusAndTimothy, Language::En, "Timothy and Titus, Companions of Saint Paul"),
    (Feast::TuesdayInEasterWeek, Language::En, "Tuesday in Easter Week"),
    (Feast::TuesdayInHolyWeek, Language::En, "Tuesday in Holy Week"),
    (Feast::VincentOfSaragossa, Language::En, "Vincent, Deacon of Saragossa, and Martyr, 304"),
    (Feast::EveOfTheAscension, Language::En, "Eve of the Ascension"),
    (Feast::WednesdayInEasterWeek, Language::En, "Wednesday in Easter Week"),
    (Feast::WednesdayInHolyWeek, Language::En, "Wednesday in Holy Week"),
    (Feast::AshWednesday, Language::En, "Ash Wednesday"),
    (Feast::WilliamAugustusMuhlenberg, Language::En, "William Augustus Muhlenberg, Priest, 1877"),
    (Feast::WilliamLaud, Language::En, "William Laud, Archbishop of Canterbury, 1645"),
    (Feast::WilliamLaw, Language::En, "William Law, Priest, 1761"),
    (Feast::WilliamPorcherDubose, Language::En, "William Porcher DuBose, Priest, 1918"),
    (Feast::WilliamReedHuntington, Language::En, "William Reed Huntington, Priest, 1909"),
    (Feast::WilliamTyndale, Language::En, "William Tyndale, Priest, 1536"),
    (Feast::WilliamWhite, Language::En, "William White, Bishop of Pennsylvania, 1836"),
    (Feast::WilliamWilberforce, Language::En, "William Wilberforce, 1833"),
    (Feast::Willibrord, Language::En, "Willibrord, Archbishop of Utrecht, Missionary to Frisia, 739"),
    (Feast::WulfstanOfWorcester, Language::En, "Wulfstan, Bishop of Worcester, 1095"),
    (Feast::December24, Language::En, "December 24"),
    (Feast::ChristmasEve, Language::En, "Christmas Eve"),
    (Feast::December29, Language::En, "December 29"),
    (Feast::December30, Language::En, "December 30"),
    (Feast::December31, Language::En, "December 31"),
    (Feast::EveOfHolyName, Language::En, "Eve of Holy Name"),
    (Feast::January2, Language::En, "January 2"),
    (Feast::January3, Language::En, "January 3"),
    (Feast::January4, Language::En, "January 4"),
    (Feast::January5, Language::En, "January 5"),
    (Feast::EveOfEpiphany, Language::En, "Eve of Epiphany"),
];

pub(crate) const BCP1979_WEEK_NAMES: [(LiturgicalWeek, Language, &str); 59] = [
    (
        LiturgicalWeek::Pentecost10,
        Language::En,
        "The Tenth Sunday after Pentecost",
    ),
    (
        LiturgicalWeek::Pentecost11,
        Language::En,
        "The Eleventh Sunday after Pentecost",
    ),
    (
        LiturgicalWeek::Pentecost12,
        Language::En,
        "The Twelfth Sunday after Pentecost",
    ),
    (
        LiturgicalWeek::Pentecost13,
        Language::En,
        "The Thirteenth Sunday after Pentecost",
    ),
    (
        LiturgicalWeek::Pentecost14,
        Language::En,
        "The Fourteenth Sunday after Pentecost",
    ),
    (
        LiturgicalWeek::Pentecost15,
        Language::En,
        "The Fifteenth Sunday after Pentecost",
    ),
    (
        LiturgicalWeek::Pentecost16,
        Language::En,
        "The Sixteenth Sunday after Pentecost",
    ),
    (
        LiturgicalWeek::Pentecost17,
        Language::En,
        "The Seventeenth Sunday after Pentecost",
    ),
    (
        LiturgicalWeek::Pentecost18,
        Language::En,
        "The Eighteenth Sunday after Pentecost",
    ),
    (
        LiturgicalWeek::Pentecost19,
        Language::En,
        "The Nineteenth Sunday after Pentecost",
    ),
    (
        LiturgicalWeek::Epiphany1,
        Language::En,
        "The First Sunday after the Epiphany",
    ),
    (
        LiturgicalWeek::Lent1,
        Language::En,
        "The First Sunday in Lent",
    ),
    (
        LiturgicalWeek::Christmas1,
        Language::En,
        "The First Sunday after Christmas",
    ),
    (
        LiturgicalWeek::Pentecost20,
        Language::En,
        "The Twentieth Sunday after Pentecost",
    ),
    (
        LiturgicalWeek::Pentecost21,
        Language::En,
        "The Twenty-First Sunday after Pentecost",
    ),
    (
        LiturgicalWeek::Pentecost22,
        Language::En,
        "The Twenty-Second Sunday after Pentecost",
    ),
    (
        LiturgicalWeek::Pentecost23,
        Language::En,
        "The Twenty-Third Sunday after Pentecost",
    ),
    (
        LiturgicalWeek::Pentecost24,
        Language::En,
        "The Twenty-Fourth Sunday after Pentecost",
    ),
    (
        LiturgicalWeek::Pentecost25,
        Language::En,
        "The Twenty-Fifth Sunday after Pentecost",
    ),
    (
        LiturgicalWeek::Pentecost26,
        Language::En,
        "The Twenty-Sixth Sunday after Pentecost",
    ),
    (
        LiturgicalWeek::Pentecost27,
        Language::En,
        "The Twenty-Seventh Sunday after Pentecost",
    ),
    (
        LiturgicalWeek::Easter2,
        Language::En,
        "The Second Sunday of Easter",
    ),
    (
        LiturgicalWeek::Epiphany2,
        Language::En,
        "The Second Sunday after the Epiphany",
    ),
    (
        LiturgicalWeek::Lent2,
        Language::En,
        "The Second Sunday in Lent",
    ),
    (
        LiturgicalWeek::Pentecost2,
        Language::En,
        "The Second Sunday after Pentecost",
    ),
    (
        LiturgicalWeek::Christmas2,
        Language::En,
        "The Second Sunday after Christmas",
    ),
    (
        LiturgicalWeek::Easter3,
        Language::En,
        "The Third Sunday of Easter",
    ),
    (
        LiturgicalWeek::Epiphany3,
        Language::En,
        "The Third Sunday after the Epiphany",
    ),
    (
        LiturgicalWeek::Lent3,
        Language::En,
        "The Third Sunday in Lent",
    ),
    (
        LiturgicalWeek::Pentecost3,
        Language::En,
        "The Third Sunday after Pentecost",
    ),
    (
        LiturgicalWeek::Easter4,
        Language::En,
        "The Fourth Sunday of Easter",
    ),
    (
        LiturgicalWeek::Epiphany4,
        Language::En,
        "The Fourth Sunday after the Epiphany",
    ),
    (
        LiturgicalWeek::Lent4,
        Language::En,
        "The Fourth Sunday in Lent",
    ),
    (
        LiturgicalWeek::Pentecost4,
        Language::En,
        "The Fourth Sunday after Pentecost",
    ),
    (
        LiturgicalWeek::Easter5,
        Language::En,
        "The Fifth Sunday of Easter",
    ),
    (
        LiturgicalWeek::Epiphany5,
        Language::En,
        "The Fifth Sunday after the Epiphany",
    ),
    (
        LiturgicalWeek::Lent5,
        Language::En,
        "The Fifth Sunday in Lent",
    ),
    (
        LiturgicalWeek::Pentecost5,
        Language::En,
        "The Fifth Sunday after Pentecost",
    ),
    (
        LiturgicalWeek::Easter6,
        Language::En,
        "The Sixth Sunday of Easter",
    ),
    (
        LiturgicalWeek::Epiphany6,
        Language::En,
        "The Sixth Sunday after the Epiphany",
    ),
    (
        LiturgicalWeek::Pentecost6,
        Language::En,
        "The Sixth Sunday after Pentecost",
    ),
    (
        LiturgicalWeek::Easter7,
        Language::En,
        "The Seventh Sunday of Easter",
    ),
    (
        LiturgicalWeek::Epiphany7,
        Language::En,
        "The Seventh Sunday after the Epiphany",
    ),
    (
        LiturgicalWeek::Pentecost7,
        Language::En,
        "The Seventh Sunday after Pentecost",
    ),
    (
        LiturgicalWeek::Epiphany8,
        Language::En,
        "The Eighth Sunday after the Epiphany",
    ),
    (
        LiturgicalWeek::Pentecost8,
        Language::En,
        "The Eighth Sunday after Pentecost",
    ),
    (
        LiturgicalWeek::Pentecost9,
        Language::En,
        "The Ninth Sunday after Pentecost",
    ),
    (LiturgicalWeek::Christmas, Language::En, "Christmas"),
    (LiturgicalWeek::Easter, Language::En, "Easter Day"),
    (LiturgicalWeek::Epiphany, Language::En, "Epiphany"),
    (
        LiturgicalWeek::Advent1,
        Language::En,
        "The First Sunday of Advent",
    ),
    (
        LiturgicalWeek::Advent4,
        Language::En,
        "The Fourth Sunday of Advent",
    ),
    (LiturgicalWeek::HolyWeek, Language::En, "Palm Sunday"),
    (
        LiturgicalWeek::LastPentecost,
        Language::En,
        "The Last Sunday after Pentecost",
    ),
    (
        LiturgicalWeek::LastEpiphany,
        Language::En,
        "The Last Sunday after the Epiphany",
    ),
    (LiturgicalWeek::Pentecost, Language::En, "Pentecost"),
    (
        LiturgicalWeek::Advent2,
        Language::En,
        "The Second Sunday of Advent",
    ),
    (
        LiturgicalWeek::Advent3,
        Language::En,
        "The Third Sunday of Advent",
    ),
    (
        LiturgicalWeek::TrinitySunday,
        Language::En,
        "Trinity Sunday",
    ),
];

pub(crate) const BCP1979_PROPER_NAMES: [(Proper, Language, &str); 29] = [
    (Proper::Proper1, Language::En, "Proper 1"),
    (Proper::Proper2, Language::En, "Proper 2"),
    (Proper::Proper3, Language::En, "Proper 3"),
    (Proper::Proper4, Language::En, "Proper 4"),
    (Proper::Proper5, Language::En, "Proper 5"),
    (Proper::Proper6, Language::En, "Proper 6"),
    (Proper::Proper7, Language::En, "Proper 7"),
    (Proper::Proper8, Language::En, "Proper 8"),
    (Proper::Proper9, Language::En, "Proper 9"),
    (Proper::Proper10, Language::En, "Proper 10"),
    (Proper::Proper11, Language::En, "Proper 11"),
    (Proper::Proper12, Language::En, "Proper 12"),
    (Proper::Proper13, Language::En, "Proper 13"),
    (Proper::Proper14, Language::En, "Proper 14"),
    (Proper::Proper15, Language::En, "Proper 15"),
    (Proper::Proper16, Language::En, "Proper 16"),
    (Proper::Proper17, Language::En, "Proper 17"),
    (Proper::Proper18, Language::En, "Proper 18"),
    (Proper::Proper19, Language::En, "Proper 19"),
    (Proper::Proper20, Language::En, "Proper 20"),
    (Proper::Proper21, Language::En, "Proper 21"),
    (Proper::Proper22, Language::En, "Proper 22"),
    (Proper::Proper23, Language::En, "Proper 23"),
    (Proper::Proper24, Language::En, "Proper 24"),
    (Proper::Proper25, Language::En, "Proper 25"),
    (Proper::Proper26, Language::En, "Proper 26"),
    (Proper::Proper27, Language::En, "Proper 27"),
    (Proper::Proper28, Language::En, "Proper 28"),
    (Proper::Proper29, Language::En, "Proper 29"),
];

#[cfg(test)]
mod tests {
    use crate::LiturgicalDayId;

    use super::super::*;

    #[test]
    fn thanksgiving_day() {
        let tday = BCP1979_CALENDAR.liturgical_day(Date::from_ymd(2021, 11, 25), false);
        assert_eq!(
            tday.observed,
            LiturgicalDayId::Feast(Feast::ThanksgivingDay)
        );
        let tday = BCP1979_CALENDAR.liturgical_day(Date::from_ymd(2017, 11, 23), false);
        assert_eq!(
            tday.observed,
            LiturgicalDayId::Feast(Feast::ThanksgivingDay)
        );
    }

    #[test]
    fn last_week_after_epiphany() {
        let tday = BCP1979_CALENDAR
            .liturgical_day_without_transferred_feasts(Date::from_ymd(2022, 2, 28), false);
        assert_eq!(
            tday.observed,
            LiturgicalDayId::WeekAndDay(LiturgicalWeek::LastEpiphany, Weekday::Mon)
        );
    }
}
