[package]
name = "reference-parser"
version = "0.1.0"
edition = "2018"

[dependencies]
regex = "1"
strsim = "0.10"
serde = { version = "1.0", features = ["derive"] }
language = { path = "../language" }